(function () {
  "use strict";
  var API = "/api";
  var state = { athletes: [], events: [], cities: [], marks: [], users: [], translations: [] };
  var currentUser = null;
  function byId(id) { return document.getElementById(id); }
  function t(value) { return window.RankingI18n.t(value); }
  function escapeHtml(value) { return String(value == null ? "" : value).replace(/[&<>"']/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]; }); }
  function normalized(value) { return String(value || "").trim().toLocaleLowerCase("ca").normalize("NFD").replace(/[\u0300-\u036f]/g, ""); }
  function byValue(items, id) { return items.find(function (item) { return String(item.id) === String(id); }); }
  function areaLabel(area) { return { pista_cubierta: "Pista Cubierta", aire_libre: "Aire Libre", ruta: "Ruta" }[area] || area; }
  function eventLabel(item) { return t(areaLabel(item.area)) + " / " + t(item.eventGroup) + " / " + t(item.name); }
  function categoryLabel(value) { var parts = String(value || "").split(" - "); parts[0] = parts[0].replace(/^Master /, t("Master") + " "); if (parts[0] === "Senior") parts[0] = t("Senior"); if (parts[1]) parts[1] = t(parts[1]); return parts.join(" - "); }
  function athleteLabel(item) { return item.name + " " + item.surname; }
  function cityLabel(item) { return item.name + (item.province ? " (" + item.province + ")" : ""); }
  function formatDate(date) { return date ? new Date(date + "T00:00:00").toLocaleDateString(window.RankingI18n.language() === "ca" ? "ca-ES" : "es-ES") : ""; }
  function today() { var d = new Date(), o = d.getTimezoneOffset() * 60000; return new Date(d.getTime() - o).toISOString().slice(0, 10); }
  function setError(prefix, value) { byId(prefix + "-error").textContent = t(value || ""); }
  async function request(path, options) { var config = options || {}; config.headers = { "Content-Type": "application/json" }; var response = await fetch(API + path, config); var data = await response.json().catch(function () { return {}; }); if (response.status === 401 && path !== "/auth/login") showAuthentication(false); if (!response.ok) throw new Error(t(data.error || "No se ha podido guardar la informacion.")); return data; }
  function showAuthentication(setup) { currentUser = null; byId("auth-shell").classList.remove("hidden"); byId("app-header").classList.add("hidden"); byId("app-shell").classList.add("hidden"); byId("app-footer").classList.add("hidden"); byId("login-form").classList.toggle("hidden", setup); byId("setup-form").classList.toggle("hidden", !setup); }
  function showApplication(user) { currentUser = user; byId("auth-shell").classList.add("hidden"); byId("app-header").classList.remove("hidden"); byId("app-shell").classList.remove("hidden"); byId("app-footer").classList.remove("hidden"); byId("current-user-name").textContent = user.name; }
  function status(id, message, failure) { var el = byId(id); el.textContent = t(message); el.classList.remove("hidden"); el.classList.toggle("failure", Boolean(failure)); }
  function showAppError(message) { byId("app-error").textContent = t(message || ""); byId("app-error").classList.toggle("hidden", !message); }
  function switchPanel(name) { document.querySelectorAll(".tab").forEach(function (tab) { tab.classList.toggle("active", tab.dataset.panel === name); }); document.querySelectorAll(".panel").forEach(function (panel) { panel.classList.toggle("active", panel.id === "panel-" + name); }); }
  async function refresh() { try { state = await request("/bootstrap"); if (window.RankingI18n.setManagedTranslations) window.RankingI18n.setManagedTranslations(state.translations); render(); showAppError(""); } catch (error) { showAppError(error.message); throw error; } }
  async function initialize() { try { var auth = await request("/auth/status"); if (!auth.user) { showAuthentication(auth.setupRequired); return; } showApplication(auth.user); try { await refresh(); } catch (error) { /* The session remains valid; the app displays the data-loading error. */ } } catch (error) { showAuthentication(false); byId("login-error").textContent = error.message; } }

  function age(birthdate, date) { if (!birthdate || !date || date < birthdate) return null; var b = new Date(birthdate + "T00:00:00"), d = new Date(date + "T00:00:00"); var n = d.getFullYear() - b.getFullYear(); if (d.getMonth() < b.getMonth() || (d.getMonth() === b.getMonth() && d.getDate() < b.getDate())) n -= 1; return n; }
  function category(athlete, date) { var n = age(athlete.birthdate, date); if (n === null) return null; var base = n < 8 ? "Sub8" : n < 10 ? "Sub10" : n < 12 ? "Sub12" : n < 14 ? "Sub14" : n < 16 ? "Sub16" : n < 18 ? "Sub18" : n < 20 ? "Sub20" : n < 23 ? "Sub23" : n < 35 ? "Senior" : "Master " + Math.min(100, Math.floor(n / 5) * 5); return base + " - " + (athlete.sex === "femenino" ? "Femenino" : "Masculino"); }
  function selectedAthlete() { var value = normalized(byId("mark-athlete").value); return state.athletes.find(function (a) { return normalized(athleteLabel(a)) === value; }); }
  function selectedCity(input) { var value = normalized(input); return state.cities.find(function (c) { return normalized(cityLabel(c)) === value || normalized(c.name) === value; }); }
  function selectedImportAthlete() { var value = normalized(byId("mark-import-athlete").value); return state.athletes.find(function (a) { return normalized(athleteLabel(a)) === value; }); }
  function currentEvent() { return byValue(state.events, byId("mark-event").value); }
  function updateCategory() { var athlete = selectedAthlete(), result = athlete ? category(athlete, byId("mark-date").value) : null; byId("mark-category").textContent = result ? categoryLabel(result) : t("Selecciona atleta y fecha"); }
  function renderEventSelect(selected) { var area = byId("mark-area").value; var events = state.events.filter(function (item) { return item.area === area; }); byId("mark-event").innerHTML = events.map(function (item) { return "<option value=\"" + item.id + "\">" + escapeHtml(t(item.eventGroup) + " / " + t(item.name)) + "</option>"; }).join(""); if (selected) byId("mark-event").value = String(selected); updateMarkFields(); }
  function updateMarkFields() { var item = currentEvent(), isTrack = byId("mark-area").value !== "ruta"; byId("track-name-field").classList.toggle("hidden", !isTrack); byId("technical-field").classList.toggle("hidden", !(item && Number(item.requiresTechnicalInfo))); byId("mark-technical-info").required = Boolean(item && Number(item.requiresTechnicalInfo)); }
  function renderOptions() { byId("athlete-options").innerHTML = state.athletes.map(function (a) { return "<option value=\"" + escapeHtml(athleteLabel(a)) + "\"></option>"; }).join(""); byId("city-options").innerHTML = state.cities.map(function (c) { return "<option value=\"" + escapeHtml(cityLabel(c)) + "\"></option>"; }).join(""); renderEventSelect(byId("mark-event").value); }
  function renderAthletes() { byId("athletes-body").innerHTML = state.athletes.map(function (a) { return "<tr><td><strong>" + escapeHtml(athleteLabel(a)) + "</strong></td><td>" + formatDate(a.birthdate) + "</td><td>" + escapeHtml(t(a.sex === "femenino" ? "Femenino" : "Masculino")) + "</td><td class=\"row-actions\"><button class=\"row-button\" data-edit-athlete=\"" + a.id + "\">" + t("Editar") + "</button><button class=\"row-button danger\" data-delete-athlete=\"" + a.id + "\">" + t("Eliminar") + "</button></td></tr>"; }).join(""); byId("athletes-empty").classList.toggle("hidden", state.athletes.length > 0); }
  function renderEvents() { byId("events-body").innerHTML = state.events.map(function (item) { return "<tr><td>" + escapeHtml(t(areaLabel(item.area)) + " / " + t(item.eventGroup)) + "</td><td><strong>" + escapeHtml(t(item.name)) + "</strong></td><td>" + t(item.resultDirection === "higher" ? "Marca mas alta" : "Marca mas baja") + "</td><td>" + (Number(item.requiresTechnicalInfo) ? t("Si") : t("No")) + "</td></tr>"; }).join(""); byId("events-empty").classList.toggle("hidden", state.events.length > 0); }
  function renderCities() { byId("cities-body").innerHTML = state.cities.slice(0, 500).map(function (c) { return "<tr><td>" + escapeHtml(c.name) + "</td><td>" + escapeHtml(c.province) + "</td></tr>"; }).join(""); byId("cities-empty").classList.toggle("hidden", state.cities.length > 0); }
  function translationRows() { var rows = window.RankingI18n.availableTranslations ? window.RankingI18n.availableTranslations() : []; var byLiteral = Object.create(null); function add(literal) { if (literal && !byLiteral[literal]) byLiteral[literal] = { literal: literal, es: literal, ca: t(literal) }; } rows.forEach(function (row) { byLiteral[row.literal] = row; }); state.events.forEach(function (event) { add(event.name); add(event.eventGroup); }); ["Sub8", "Sub10", "Sub12", "Sub14", "Sub16", "Sub18", "Sub20", "Sub23", "Senior", "Master", "Femenino", "Masculino"].forEach(add); state.translations.forEach(function (custom) { byLiteral[custom.literal] = { id: custom.id, literal: custom.literal, es: custom.es, ca: custom.ca }; }); return Object.keys(byLiteral).map(function (key) { return byLiteral[key]; }).sort(function (a, b) { return a.literal.localeCompare(b.literal, "ca"); }); }
  function renderTranslations() { var rows = translationRows(); byId("translations-body").innerHTML = rows.map(function (x) { var remove = x.id ? "<button class=\"row-button danger\" data-delete-translation=\"" + x.id + "\">" + t("Eliminar") + "</button>" : ""; return "<tr><td>" + escapeHtml(x.literal) + "</td><td>" + escapeHtml(x.es) + "</td><td>" + escapeHtml(x.ca) + "</td><td class=\"row-actions\"><button class=\"row-button\" data-edit-translation-literal=\"" + escapeHtml(encodeURIComponent(x.literal)) + "\">" + t("Editar") + "</button>" + remove + "</td></tr>"; }).join(""); byId("translations-empty").classList.toggle("hidden", rows.length > 0); }
  function renderUsers() { byId("users-body").innerHTML = state.users.map(function (u) { return "<tr><td>" + escapeHtml(u.name) + "</td><td>" + escapeHtml(u.username) + "</td><td>" + t(u.active ? "Activo" : "Inactivo") + "</td><td class=\"row-actions\"><button class=\"row-button\" data-edit-user=\"" + u.id + "\">" + t("Editar") + "</button><button class=\"row-button danger\" data-delete-user=\"" + u.id + "\">" + t("Eliminar") + "</button></td></tr>"; }).join(""); byId("users-empty").classList.toggle("hidden", state.users.length > 0); }
  function filteredMarks() { var q = normalized(byId("marks-athlete-filter").value); if (!q) return []; var ids = state.athletes.filter(function (a) { return normalized(athleteLabel(a)).includes(q); }).map(function (a) { return String(a.id); }); return state.marks.filter(function (m) { return ids.includes(String(m.athleteId)); }); }
  function renderMarks() { var rows = filteredMarks(); byId("marks-body").innerHTML = rows.map(function (m) { var e = byValue(state.events, m.eventId), c = byValue(state.cities, m.cityId); return "<tr><td>" + escapeHtml(e ? eventLabel(e) : "") + "</td><td>" + escapeHtml(m.result) + "</td><td>" + escapeHtml(categoryLabel(m.category)) + "</td><td>" + formatDate(m.date) + "</td><td>" + escapeHtml(c ? cityLabel(c) + (m.trackName ? " - " + m.trackName : "") : "") + "</td><td class=\"row-actions\"><button class=\"row-button\" data-edit-mark=\"" + m.id + "\">" + t("Editar") + "</button><button class=\"row-button danger\" data-delete-mark=\"" + m.id + "\">" + t("Eliminar") + "</button></td></tr>"; }).join(""); byId("marks-empty").classList.toggle("hidden", rows.length > 0); }
  function render() { renderOptions(); renderAthletes(); renderEvents(); renderCities(); renderTranslations(); renderUsers(); renderMarks(); byId("count-athletes").textContent = state.athletes.length; byId("count-events").textContent = state.events.length; byId("count-marks").textContent = state.marks.length; updateCategory(); }

  function reset(prefix) { byId(prefix + "-form").reset(); setError(prefix, ""); byId(prefix + "-id").value = ""; var cancel = byId("cancel-" + prefix); if (cancel) cancel.classList.add("hidden"); if (prefix === "mark") { byId("mark-date").value = today(); renderEventSelect(); updateCategory(); } if (prefix === "user") { byId("user-password").required = true; byId("user-active").checked = true; } }
  async function saveAthlete(e) { e.preventDefault(); var id = byId("athlete-id").value; try { await request("/athletes" + (id ? "/" + id : ""), { method: id ? "PUT" : "POST", body: JSON.stringify({ name: byId("athlete-name").value, surname: byId("athlete-surname").value, birthdate: byId("athlete-birthdate").value, sex: byId("athlete-sex").value }) }); reset("athlete"); await refresh(); } catch (error) { setError("athlete", error.message); } }
  async function saveMark(e) { e.preventDefault(); var athlete = selectedAthlete(), city = selectedCity(byId("mark-city").value), item = currentEvent(); if (!athlete || !city || !item) { setError("mark", "Selecciona un atleta, una prueba y una ciudad existentes."); return; } try { var id = byId("mark-id").value; await request("/marks" + (id ? "/" + id : ""), { method: id ? "PUT" : "POST", body: JSON.stringify({ athleteId: athlete.id, eventId: item.id, cityId: city.id, date: byId("mark-date").value, result: byId("mark-result").value, trackName: byId("mark-track-name").value, technicalInfo: byId("mark-technical-info").value }) }); reset("mark"); await refresh(); } catch (error) { setError("mark", error.message); } }
  async function saveTranslation(e) { e.preventDefault(); var id = byId("translation-id").value; try { await request("/translations" + (id ? "/" + id : ""), { method: id ? "PUT" : "POST", body: JSON.stringify({ literal: byId("translation-literal").value, es: byId("translation-es").value, ca: byId("translation-ca").value }) }); reset("translation"); await refresh(); } catch (error) { setError("translation", error.message); } }
  async function saveUser(e) { e.preventDefault(); var id = byId("user-id").value, payload = { name: byId("user-name").value, username: byId("user-username").value, active: byId("user-active").checked }; if (!id || byId("user-password").value) payload.password = byId("user-password").value; try { await request("/users" + (id ? "/" + id : ""), { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }); reset("user"); await refresh(); } catch (error) { setError("user", error.message); } }
  async function remove(resource, id, prefix) { try { await request("/" + resource + "/" + id, { method: "DELETE" }); reset(prefix); await refresh(); } catch (error) { setError(prefix, error.message); } }
  function editAthlete(id) { var x = byValue(state.athletes, id); byId("athlete-id").value=x.id;byId("athlete-name").value=x.name;byId("athlete-surname").value=x.surname;byId("athlete-birthdate").value=x.birthdate;byId("athlete-sex").value=x.sex;byId("cancel-athlete").classList.remove("hidden");switchPanel("atletas"); }
  function editTranslation(literal) { var x=translationRows().find(function (row) { return row.literal === literal; }); if (!x) return; byId("translation-id").value=x.id || "";byId("translation-literal").value=x.literal;byId("translation-es").value=x.es;byId("translation-ca").value=x.ca;byId("cancel-translation").classList.remove("hidden");switchPanel("traducciones"); }
  function editMark(id) { var x=byValue(state.marks,id), a=byValue(state.athletes,x.athleteId), e=byValue(state.events,x.eventId), c=byValue(state.cities,x.cityId);byId("mark-id").value=x.id;byId("mark-athlete").value=athleteLabel(a);byId("mark-area").value=e.area;renderEventSelect(e.id);byId("mark-city").value=cityLabel(c);byId("mark-date").value=x.date;byId("mark-result").value=x.result;byId("mark-track-name").value=x.trackName||"";byId("mark-technical-info").value=x.technicalInfo||"";byId("cancel-mark").classList.remove("hidden");updateCategory();switchPanel("marcas"); }
  function editUser(id) { var x=byValue(state.users,id);byId("user-id").value=x.id;byId("user-name").value=x.name;byId("user-username").value=x.username;byId("user-password").value="";byId("user-password").required=false;byId("user-active").checked=x.active;byId("cancel-user").classList.remove("hidden");switchPanel("usuarios"); }

  function parseCsv(text) { var delimiter = (text.split("\n")[0].match(/;/g)||[]).length >= (text.split("\n")[0].match(/,/g)||[]).length ? ";" : ","; return text.replace(/^\uFEFF/, "").split(/\r?\n/).filter(Boolean).map(function (line) { return line.split(delimiter).map(function (x) { return x.trim().replace(/^"|"$/g, ""); }); }); }
  function indexedRows(text) { var rows=parseCsv(text), keys=rows.shift().map(normalized); return rows.map(function(row){ var x={};keys.forEach(function(key,i){x[key]=row[i]||"";});return x;}); }
  function download(name, csv) { var link=document.createElement("a");link.href=URL.createObjectURL(new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"}));link.download=name;link.click();URL.revokeObjectURL(link.href); }
  async function importAthletes(text) { var rows=indexedRows(text).map(function(x){return {name:x.nombre,surname:x.apellidos,birthdate:x["fecha de nacimiento"]||x.fecha_nacimiento,sex:normalized(x.sexo)==="femenino"?"femenino":"masculino"};});var out=await request("/athletes/import",{method:"POST",body:JSON.stringify({athletes:rows})});await refresh();status("athlete-import-status",out.imported+" atletas importados, "+out.duplicates+" duplicados y "+out.invalid+" no válidos.",out.invalid>0); }
  async function importCities(text) { var rows=indexedRows(text).map(function(x){return {name:x.ciudad||x.nombre,province:x.provincia};});var out=await request("/cities/import",{method:"POST",body:JSON.stringify({cities:rows})});await refresh();status("city-import-status",out.imported+" ciudades importadas.",false); }
  async function importMarks(text) { var athlete=selectedImportAthlete();if(!athlete){status("mark-import-status","Selecciona primero el atleta al que corresponden las marcas.",true);return;}var errors=[];var rows=indexedRows(text).map(function(x,i){var city=selectedCity(x.ciudad);var event=state.events.find(function(e){return normalized(areaLabel(e.area))===normalized(x.ambito)&&normalized(e.eventGroup)===normalized(x.grupo)&&normalized(e.name)===normalized(x.prueba);});if(!city)errors.push("Fila "+(i+2)+": ciudad no existe.");if(!event)errors.push("Fila "+(i+2)+": prueba no coincide con el catálogo.");return city&&event?{cityId:city.id,eventId:event.id,result:x.marca,date:x.fecha,trackName:x.pista,technicalInfo:x["caracteristica tecnica"]}:null;}).filter(Boolean);if(errors.length){status("mark-import-status",errors.join(" "),true);return;}var out=await request("/marks/import",{method:"POST",body:JSON.stringify({athleteId:athlete.id,marks:rows})});if(out.errors.length){status("mark-import-status",out.errors.map(function(e){return "Fila "+e.row+": "+e.error;}).join(" "),true);return;}await refresh();status("mark-import-status",out.imported+" marcas importadas per a "+athleteLabel(athlete)+".",false); }
  function readFile(input, callback) { var file=input.files[0];if(!file)return;var reader=new FileReader();reader.onload=function(){callback(String(reader.result)).catch(function(error){status(input.id==="import-cities-file"?"city-import-status":input.id==="import-marks-file"?"mark-import-status":"athlete-import-status",error.message,true);});input.value="";};reader.readAsText(file); }

  byId("mark-date").value=today();
  document.querySelector(".tabs").addEventListener("click",function(e){if(e.target.dataset.panel)switchPanel(e.target.dataset.panel);});
  byId("login-form").addEventListener("submit",function(e){e.preventDefault();request("/auth/login",{method:"POST",body:JSON.stringify({username:byId("login-username").value,password:byId("login-password").value})}).then(async function(x){showApplication(x.user);try { await refresh(); } catch (error) { return; }}).catch(function(error){setError("login",error.message);});});
  byId("setup-form").addEventListener("submit",function(e){e.preventDefault();request("/auth/setup",{method:"POST",body:JSON.stringify({name:byId("setup-name").value,username:byId("setup-username").value,password:byId("setup-password").value})}).then(async function(x){showApplication(x.user);try { await refresh(); } catch (error) { return; }}).catch(function(error){setError("setup",error.message);});});
  byId("logout").addEventListener("click",function(){request("/auth/logout",{method:"POST",body:"{}"}).then(function(){showAuthentication(false);});});
  byId("athlete-form").addEventListener("submit",saveAthlete);byId("mark-form").addEventListener("submit",saveMark);byId("translation-form").addEventListener("submit",saveTranslation);byId("user-form").addEventListener("submit",saveUser);
  ["athlete","mark","translation","user"].forEach(function(x){byId("cancel-"+x).addEventListener("click",function(){reset(x);});});
  byId("mark-area").addEventListener("change",function(){renderEventSelect();});byId("mark-event").addEventListener("change",updateMarkFields);byId("mark-athlete").addEventListener("input",updateCategory);byId("mark-date").addEventListener("input",updateCategory);byId("marks-athlete-filter").addEventListener("input",renderMarks);
  byId("add-import-athlete").addEventListener("click",function(){ var parts=byId("mark-import-athlete").value.trim().split(/\s+/); reset("athlete"); if(parts.length){byId("athlete-name").value=parts.shift();byId("athlete-surname").value=parts.join(" ");} switchPanel("atletas"); });
  byId("download-athlete-template").addEventListener("click",function(){download("plantilla-atletas.csv","Nombre;Apellidos;Fecha de nacimiento;Sexo\nAnna;Garcia Lopez;2010-05-18;femenino\n");});
  byId("import-athletes-file").addEventListener("change",function(){readFile(this,importAthletes);});byId("import-cities-file").addEventListener("change",function(){readFile(this,importCities);});byId("import-marks-file").addEventListener("change",function(){readFile(this,importMarks);});
  document.body.addEventListener("click",function(e){var d=e.target.dataset;if(d.editAthlete)editAthlete(d.editAthlete);if(d.editTranslationLiteral)editTranslation(decodeURIComponent(d.editTranslationLiteral));if(d.editMark)editMark(d.editMark);if(d.editUser)editUser(d.editUser);if(d.deleteAthlete)remove("athletes",d.deleteAthlete,"athlete");if(d.deleteTranslation)remove("translations",d.deleteTranslation,"translation");if(d.deleteMark)remove("marks",d.deleteMark,"mark");if(d.deleteUser)remove("users",d.deleteUser,"user");});
  document.addEventListener("rankinglanguagechange",render);
  initialize();
}());
