(function () {
  "use strict";
  var API = "/api";
  var state = { athletes: [], events: [], cities: [], tracks: [], marks: [], deletedMarks: [], users: [], translations: [] };
  var currentUser = null;
  var pendingMultiMarks = [];
  var pendingSingleMarks = [];
  var editingAthleteId = null;
  var editingMarkId = null;
  var editingTrackId = null;
  function byId(id) { return document.getElementById(id); }
  function t(value) { return window.RankingI18n.t(value); }
  function escapeHtml(value) { return String(value == null ? "" : value).replace(/[&<>"']/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]; }); }
  function normalized(value) { return String(value || "").trim().toLocaleLowerCase("ca").normalize("NFD").replace(/[\u0300-\u036f]/g, ""); }
  function byValue(items, id) { return items.find(function (item) { return String(item.id) === String(id); }); }
  function areaLabel(area) { return { pista_cubierta: "Pista Cubierta", aire_libre: "Aire Libre", ruta: "Ruta" }[area] || area; }
  function groupLabel(group) { return t(normalized(group) === "llancaments" ? "Llançaments" : group); }
  function eventLabel(item) { return t(areaLabel(item.area)) + " / " + groupLabel(item.eventGroup) + " / " + t(item.name || item.event); }
  function raceDistance(item) { var name = normalized(item.name).replace(",", "."), match, group = normalized(item.eventGroup); if (group !== "curses" && group !== "tanques") return null; if (name === "milla") return 1609; if (name.indexOf("mitja") === 0) return 21097; if (name === "marato") return 42195; match = /^(\d+(?:\.\d+)?)\s*(km)?/.exec(name); return match ? Number(match[1]) * (match[2] ? 1000 : 1) : null; }
  function compareEvents(first, second) { var areas = ["pista_cubierta", "aire_libre", "ruta"], scope = areas.indexOf(first.area) - areas.indexOf(second.area); if (scope) return scope; var group = groupLabel(first.eventGroup).localeCompare(groupLabel(second.eventGroup)); if (group) return group; var firstDistance = raceDistance(first), secondDistance = raceDistance(second); if (firstDistance !== null && secondDistance !== null) return firstDistance - secondDistance; return t(first.name).localeCompare(t(second.name)); }
  function categoryLabel(value) { var parts = String(value || "").split(" - "); parts[0] = parts[0].replace(/^Master /, t("Master") + " "); if (parts[0] === "Senior") parts[0] = t("Senior"); if (parts[1]) parts[1] = t(parts[1]); return parts.join(" - "); }
  function athleteLabel(item) { return item.name + " " + item.surname; }
  function cityLabel(item) { return item.name + (item.province ? " (" + item.province + ")" : ""); }
  function detailLine(value, label) { return value ? "<span class=\"cell-detail\">" + (label ? "<span class=\"cell-detail-label\">" + escapeHtml(label) + ":</span> " : "") + escapeHtml(value) + "</span>" : ""; }
  function technicalValue(value) { return normalized(value) === "no" ? "" : String(value || ""); }
  function technicalDetail(value) { return detailLine(technicalValue(value), t("Marca técnica")); }
  function markResultCell(mark) { return "<span class=\"mark-result-main\">" + escapeHtml(normalizeResultText(mark.result)) + "</span>" + technicalDetail(mark.technicalInfo); }
  function formatDate(date) { return date ? new Date(date + "T00:00:00").toLocaleDateString(window.RankingI18n.language() === "ca" ? "ca-ES" : "es-ES") : ""; }
  function normalizeResultText(value) { var result = String(value == null ? "" : value).trim(), hour = /^(\d+)[hH](\d{1,2})['’](\d{1,2})"(\d{0,2})$/.exec(result), minute, decimal; if (hour) { decimal = hour[4] || "0"; decimal = decimal.length === 1 ? decimal + "0" : decimal.slice(0, 2); return String(Number(hour[1])) + ":" + String(Number(hour[2])).padStart(2, "0") + ":" + String(Number(hour[3])).padStart(2, "0") + "." + decimal.padStart(2, "0"); } minute = /^(\d+)['’](\d{1,2})"(\d{0,2})$/.exec(result); if (minute) { decimal = minute[3] || "0"; decimal = decimal.length === 1 ? decimal + "0" : decimal.slice(0, 2); return String(Number(minute[1])) + ":" + String(Number(minute[2])).padStart(2, "0") + "." + decimal.padStart(2, "0"); } var quotedMinute = /^(\d+)"(\d{1,2})"$/.exec(result); if (quotedMinute) return String(Number(quotedMinute[1])) + ":" + String(Number(quotedMinute[2])).padStart(2, "0") + ".00"; var second = /^(\d+)"(\d{1,2})$/.exec(result); if (second) return "00:" + String(Number(second[1])).padStart(2, "0") + "." + second[2]; if (/^\d+,\d+$/.test(result)) return result.replace(",", "."); return result; }
  function csvEscape(value) { var text = String(value == null ? "" : value); return /[;"\n\r]/.test(text) ? '"' + text.replace(/"/g, '""') + '"' : text; }
  function today() { var d = new Date(), o = d.getTimezoneOffset() * 60000; return new Date(d.getTime() - o).toISOString().slice(0, 10); }
  function setError(prefix, value) { byId(prefix + "-error").textContent = t(value || ""); }
  function isAdmin() { return currentUser && currentUser.role === "admin"; }
  function isMarksManager() { return currentUser && currentUser.role === "marks_manager"; }
  function hasGlobalMarkAccess() { return isAdmin() || isMarksManager(); }
  function permissionMap(user) { var map = {}; (user && user.permissions || []).forEach(function (p) { map[String(p.athleteId)] = p; }); return map; }
  function allowedPanels() { return isAdmin() ? null : (isMarksManager() ? ["control", "marcas", "consulta-marcas"] : ["control", "marcas", "consulta-marcas", "atletas"]); }
  function applyAccessUi() {
    var panels = allowedPanels();
    document.querySelectorAll(".tab").forEach(function (tab) { tab.classList.toggle("hidden", panels && panels.indexOf(tab.dataset.panel) === -1); });
    document.querySelectorAll(".admin-only").forEach(function (item) { item.classList.toggle("hidden", !isAdmin()); });
    byId("replace-marks-form").classList.toggle("hidden", !hasGlobalMarkAccess());
    if (panels && panels.indexOf(document.querySelector(".tab.active").dataset.panel) === -1) switchPanel("marcas");
  }
  async function request(path, options) { var config = options || {}; config.headers = { "Content-Type": "application/json" }; var response = await fetch(API + path, config); var data = await response.json().catch(function () { return {}; }); if (response.status === 401 && path !== "/auth/login") showAuthentication(false); if (!response.ok) throw new Error(t(data.error || "No se ha podido guardar la informacion.")); return data; }
  function showAuthentication(setup) { currentUser = null; byId("auth-shell").classList.remove("hidden"); byId("app-top-actions").classList.add("hidden"); byId("app-header").classList.add("hidden"); byId("app-shell").classList.add("hidden"); byId("app-footer").classList.add("hidden"); byId("login-form").classList.toggle("hidden", setup); byId("setup-form").classList.toggle("hidden", !setup); }
  function showApplication(user) { currentUser = user; byId("auth-shell").classList.add("hidden"); byId("app-top-actions").classList.remove("hidden"); byId("app-header").classList.remove("hidden"); byId("app-shell").classList.remove("hidden"); byId("app-footer").classList.remove("hidden"); byId("current-user-name").textContent = user.name; byId("welcome-user").classList.remove("hidden"); applyAccessUi(); }
  function status(id, message, failure) { var el = byId(id); el.textContent = t(message); el.classList.remove("hidden"); el.classList.toggle("failure", Boolean(failure)); }
  function showAppError(message) { byId("app-error").textContent = t(message || ""); byId("app-error").classList.toggle("hidden", !message); }
  function switchPanel(name) { document.querySelectorAll(".tab").forEach(function (tab) { tab.classList.toggle("active", tab.dataset.panel === name); }); document.querySelectorAll(".panel").forEach(function (panel) { panel.classList.toggle("active", panel.id === "panel-" + name); }); }
  async function refresh() { try { state = await request("/bootstrap"); if (window.RankingI18n.setManagedTranslations) window.RankingI18n.setManagedTranslations(state.translations); render(); applyAccessUi(); showAppError(""); } catch (error) { showAppError(error.message); throw error; } }
  async function initialize() { try { var auth = await request("/auth/status"); if (!auth.user) { showAuthentication(auth.setupRequired); return; } showApplication(auth.user); try { await refresh(); } catch (error) { /* The session remains valid; the app displays the data-loading error. */ } } catch (error) { showAuthentication(false); byId("login-error").textContent = error.message; } }

  function ages(birthdate, date) { if (!birthdate || !date || date < birthdate) return null; var b = new Date(birthdate + "T00:00:00"), d = new Date(date + "T00:00:00"), exact = d.getFullYear() - b.getFullYear(), calendar = exact; if (d.getMonth() < b.getMonth() || (d.getMonth() === b.getMonth() && d.getDate() < b.getDate())) exact -= 1; return { exact: exact, calendar: calendar }; }
  function category(athlete, date) { var n = ages(athlete.birthdate, date); if (n === null) return null; var base = n.exact >= 35 ? "Master " + Math.min(100, Math.floor(n.exact / 5) * 5) : n.calendar < 8 ? "Sub8" : n.calendar < 10 ? "Sub10" : n.calendar < 12 ? "Sub12" : n.calendar < 14 ? "Sub14" : n.calendar < 16 ? "Sub16" : n.calendar < 18 ? "Sub18" : n.calendar < 20 ? "Sub20" : n.calendar < 23 ? "Sub23" : "Senior"; return base + " - " + (athlete.sex === "femenino" ? "Femenino" : "Masculino"); }
  function selectedAthlete() { var value = normalized(byId("mark-athlete").value); return state.athletes.find(function (a) { return normalized(athleteLabel(a)) === value; }); }
  function canEditAthleteMarks(id) { var athlete = byValue(state.athletes, id); return hasGlobalMarkAccess() || Boolean(athlete && athlete.canEditMarks); }
  function athleteFromInput(id) { var value = normalized(byId(id).value); return state.athletes.find(function (a) { return normalized(athleteLabel(a)) === value; }); }
  function selectedCity(input) { var value = normalized(input); return state.cities.find(function (c) { return normalized(cityLabel(c)) === value || normalized(c.name) === value; }); }
  function selectedImportAthlete() { var value = normalized(byId("mark-import-athlete").value); return state.athletes.find(function (a) { return normalized(athleteLabel(a)) === value; }); }
  function currentEvent() { return byValue(state.events, byId("mark-event").value); }
  function updateCategory() { var athlete = selectedAthlete(), result = athlete ? category(athlete, byId("mark-date").value) : null; byId("mark-category").textContent = result ? categoryLabel(result) : t("Selecciona atleta y fecha"); }
  function renderEventSelect(selected) { var area = byId("mark-area").value; var events = state.events.filter(function (item) { return item.area === area; }).sort(compareEvents); byId("mark-event").innerHTML = events.map(function (item) { return "<option value=\"" + item.id + "\">" + escapeHtml(groupLabel(item.eventGroup) + " / " + t(item.name)) + "</option>"; }).join(""); if (selected) byId("mark-event").value = String(selected); updateMarkFields(); }
  function tracksFor(area, cityId) { return (state.tracks || []).filter(function (track) { return track.area === area && String(track.cityId) === String(cityId); }).sort(function (a, b) { return a.name.localeCompare(b.name, "ca"); }); }
  function selectedTrackName() { return byId("track-select-field").classList.contains("hidden") || byId("mark-track-select").value === "__new__" ? byId("mark-track-name").value : byId("mark-track-select").value; }
  function inlineTrackHtml(id, area, cityId, current) { var tracks=cityId?tracksFor(area,cityId):[], value=String(current||""), hasCurrent=tracks.some(function(track){return track.name===value;}); if(!tracks.length)return "<input data-mark-track=\""+id+"\" value=\""+escapeHtml(value)+"\" placeholder=\""+escapeHtml(t("Instalación"))+"\">"; return "<select data-mark-track-select=\""+id+"\">"+tracks.map(function(track){return "<option value=\""+escapeHtml(track.name)+"\""+(track.name===value?" selected":"")+">"+escapeHtml(track.name)+"</option>";}).join("")+(value&&!hasCurrent?"<option value=\""+escapeHtml(value)+"\" selected>"+escapeHtml(value)+"</option>":"")+"<option value=\"__new__\">Afegir una nova</option></select><input class=\""+(hasCurrent||!value?"hidden":"")+"\" data-mark-track=\""+id+"\" value=\""+escapeHtml(value&&!hasCurrent?value:"")+"\" placeholder=\""+escapeHtml(t("Nombre de la pista de atletismo"))+"\">"; }
  function inlineMarkArea(id) { var event=byValue(state.events, document.querySelector("[data-mark-event=\"" + id + "\"]").value); return event ? event.area : ""; }
  function updateInlineMarkTrack(id) { var city=selectedCity(document.querySelector("[data-mark-city=\"" + id + "\"]").value), wrap=document.querySelector("[data-mark-track-wrap=\"" + id + "\"]"), oldInput=document.querySelector("[data-mark-track=\"" + id + "\"]"), oldSelect=document.querySelector("[data-mark-track-select=\"" + id + "\"]"), oldValue=oldSelect&&oldSelect.value!=="__new__"?oldSelect.value:(oldInput?oldInput.value:""); if(wrap)wrap.innerHTML=inlineTrackHtml(id, inlineMarkArea(id), city ? city.id : null, oldValue); }
  function inlineTrackValue(id) { var select=document.querySelector("[data-mark-track-select=\"" + id + "\"]"), input=document.querySelector("[data-mark-track=\"" + id + "\"]"); return select&&select.value!=="__new__"?select.value:(input?input.value:""); }
  function updateTrackChoices() { var city=selectedCity(byId("mark-city").value), area=byId("mark-area").value, isTrack=area!=="ruta", tracks=city?tracksFor(area,city.id):[]; byId("track-select-field").classList.toggle("hidden", !isTrack || tracks.length===0); byId("track-name-field").classList.toggle("hidden", !isTrack || tracks.length>0); if(!isTrack)return; if(tracks.length){byId("mark-track-select").innerHTML=tracks.map(function(track){return "<option value=\""+escapeHtml(track.name)+"\">"+escapeHtml(track.name)+"</option>";}).join("")+"<option value=\"__new__\">Afegir una nova</option>"; if(!byId("mark-track-name").value)byId("mark-track-name").value=tracks[0].name;} }
  function updateMarkFields() { var item = currentEvent(); updateTrackChoices(); byId("technical-field").classList.toggle("hidden", !(item && Number(item.requiresTechnicalInfo))); byId("mark-technical-info").required = Boolean(item && Number(item.requiresTechnicalInfo)); }
  function renderOptions() { byId("athlete-options").innerHTML = state.athletes.map(function (a) { return "<option value=\"" + escapeHtml(athleteLabel(a)) + "\"></option>"; }).join(""); byId("city-options").innerHTML = state.cities.map(function (c) { return "<option value=\"" + escapeHtml(cityLabel(c)) + "\"></option>"; }).join(""); renderEventSelect(byId("mark-event").value); }
  function updateReplaceFields() { var city = byId("replace-field").value === "city"; ["replace-search","replace-value"].forEach(function(id){ if(city) byId(id).setAttribute("list","city-options"); else byId(id).removeAttribute("list"); }); byId("replace-search").required = city; byId("replace-search").placeholder = city ? t("Buscar ciudad...") : t("Opcional"); byId("replace-value").required = true; byId("replace-value").placeholder = city ? t("Buscar ciudad...") : t("Nombre de la pista de atletismo"); byId("replace-city-field").classList.toggle("hidden", city); if (city) byId("replace-city").value = ""; }
  function renderAthletes() { byId("athletes-body").innerHTML = state.athletes.map(function (a) { var remove = isAdmin() ? "<button class=\"row-button danger\" data-delete-athlete=\"" + a.id + "\">" + t("Eliminar") + "</button>" : ""; if (String(editingAthleteId) === String(a.id)) return "<tr class=\"editing-row\"><td><input data-athlete-name=\"" + a.id + "\" value=\"" + escapeHtml(a.name) + "\"><input data-athlete-surname=\"" + a.id + "\" value=\"" + escapeHtml(a.surname) + "\"></td><td><input data-athlete-birthdate=\"" + a.id + "\" type=\"date\" value=\"" + escapeHtml(a.birthdate) + "\"></td><td><select data-athlete-sex=\"" + a.id + "\"><option value=\"femenino\"" + (a.sex === "femenino" ? " selected" : "") + ">" + t("Femenino") + "</option><option value=\"masculino\"" + (a.sex === "masculino" ? " selected" : "") + ">" + t("Masculino") + "</option></select></td><td class=\"row-actions\"><button class=\"row-button\" data-save-athlete=\"" + a.id + "\">" + t("Guardar") + "</button><button class=\"row-button\" data-cancel-inline-athlete=\"1\">" + t("Cancelar") + "</button></td></tr>"; return "<tr><td><button class=\"athlete-list-button\" type=\"button\" data-view-athlete-marks=\"" + a.id + "\">" + escapeHtml(athleteLabel(a)) + "</button></td><td>" + formatDate(a.birthdate) + "</td><td>" + escapeHtml(t(a.sex === "femenino" ? "Femenino" : "Masculino")) + "</td><td class=\"row-actions\"><button class=\"row-button\" data-edit-athlete=\"" + a.id + "\">" + t("Editar") + "</button>" + remove + "</td></tr>"; }).join(""); byId("athletes-empty").classList.toggle("hidden", state.athletes.length > 0); }
  function renderEvents() { byId("events-body").innerHTML = state.events.slice().sort(compareEvents).map(function (item) { return "<tr><td>" + escapeHtml(t(areaLabel(item.area)) + " / " + groupLabel(item.eventGroup)) + "</td><td><strong>" + escapeHtml(t(item.name)) + "</strong></td><td>" + t(item.resultDirection === "higher" ? "Marca mas alta" : "Marca mas baja") + "</td><td>" + (Number(item.requiresTechnicalInfo) ? t("Si") : t("No")) + "</td><td class=\"row-actions\"><button class=\"row-button\" data-edit-event=\"" + item.id + "\">" + t("Editar") + "</button><button class=\"row-button danger\" data-delete-event=\"" + item.id + "\">" + t("Eliminar") + "</button></td></tr>"; }).join(""); byId("events-empty").classList.toggle("hidden", state.events.length > 0); }
  function renderCities() {}
  function areaOptions(selected) { return ["pista_cubierta","aire_libre","ruta"].map(function(area){return "<option value=\""+area+"\""+(area===selected?" selected":"")+">"+escapeHtml(t(areaLabel(area)))+"</option>";}).join(""); }
  function renderTracks() { var rows=(state.tracks || []).slice().sort(function(a,b){return (areaLabel(a.area)+a.city+a.name).localeCompare(areaLabel(b.area)+b.city+b.name,"ca");}); byId("tracks-body").innerHTML=rows.map(function(track){var city=byValue(state.cities,track.cityId), cityValue=city?cityLabel(city):track.city; if(String(editingTrackId)===String(track.id)) return "<tr class=\"editing-row\"><td><select data-track-area=\""+track.id+"\">"+areaOptions(track.area)+"</select></td><td><input data-track-city=\""+track.id+"\" list=\"city-options\" value=\""+escapeHtml(cityValue)+"\"></td><td><input data-track-name=\""+track.id+"\" value=\""+escapeHtml(track.name)+"\"></td><td>"+escapeHtml(track.markCount || 0)+"</td><td class=\"row-actions\"><button class=\"row-button\" data-save-track=\""+track.id+"\">"+t("Guardar")+"</button><button class=\"row-button\" data-cancel-inline-track=\"1\">"+t("Cancelar")+"</button></td></tr>"; return "<tr><td>"+escapeHtml(t(areaLabel(track.area)))+"</td><td>"+escapeHtml(cityValue)+"</td><td><strong>"+escapeHtml(track.name)+"</strong></td><td>"+escapeHtml(track.markCount || 0)+"</td><td class=\"row-actions\"><button class=\"row-button\" data-edit-track=\""+track.id+"\">"+t("Editar")+"</button><button class=\"row-button danger\" data-delete-track=\""+track.id+"\">"+t("Eliminar")+"</button></td></tr>";}).join(""); byId("tracks-empty").classList.toggle("hidden", rows.length>0); }
  function translationRows() { var rows = window.RankingI18n.availableTranslations ? window.RankingI18n.availableTranslations() : []; var byLiteral = Object.create(null); function add(literal) { if (literal && !byLiteral[literal]) byLiteral[literal] = { literal: literal, es: literal, ca: t(literal) }; } rows.forEach(function (row) { byLiteral[row.literal] = row; }); state.events.forEach(function (event) { add(event.name); add(event.eventGroup); }); ["Sub8", "Sub10", "Sub12", "Sub14", "Sub16", "Sub18", "Sub20", "Sub23", "Senior", "Master", "Femenino", "Masculino"].forEach(add); state.translations.forEach(function (custom) { byLiteral[custom.literal] = { id: custom.id, literal: custom.literal, es: custom.es, ca: custom.ca }; }); return Object.keys(byLiteral).map(function (key) { return byLiteral[key]; }).sort(function (a, b) { return a.literal.localeCompare(b.literal, "ca"); }); }
  function renderTranslations() { var rows = translationRows(); byId("translations-body").innerHTML = rows.map(function (x) { var remove = x.id ? "<button class=\"row-button danger\" data-delete-translation=\"" + x.id + "\">" + t("Eliminar") + "</button>" : ""; return "<tr><td>" + escapeHtml(x.literal) + "</td><td>" + escapeHtml(x.es) + "</td><td>" + escapeHtml(x.ca) + "</td><td class=\"row-actions\"><button class=\"row-button\" data-edit-translation-literal=\"" + escapeHtml(encodeURIComponent(x.literal)) + "\">" + t("Editar") + "</button>" + remove + "</td></tr>"; }).join(""); byId("translations-empty").classList.toggle("hidden", rows.length > 0); }
  function renderUserPermissions(user) {
    var permissions = permissionMap(user);
    byId("user-permissions").classList.toggle("hidden", byId("user-role").value !== "normal");
    renderPermissionList("create", state.athletes.filter(function (a) { return permissions[String(a.id)] && permissions[String(a.id)].canCreate; }).map(function (a) { return a.id; }));
    renderPermissionList("edit", state.athletes.filter(function (a) { return permissions[String(a.id)] && permissions[String(a.id)].canEdit; }).map(function (a) { return a.id; }));
  }
  function permissionListId(kind) { return "user-permission-" + kind + "-list"; }
  function permissionInputId(kind) { return "user-permission-" + kind + "-input"; }
  function selectedPermissionIds(kind) { return Array.prototype.map.call(byId(permissionListId(kind)).querySelectorAll("[data-permission-athlete]"), function (chip) { return String(chip.dataset.permissionAthlete); }); }
  function renderPermissionList(kind, ids) {
    var unique = [];
    ids.forEach(function (id) { if (unique.indexOf(String(id)) === -1 && byValue(state.athletes, id)) unique.push(String(id)); });
    byId(permissionListId(kind)).innerHTML = unique.map(function (id) {
      var athlete = byValue(state.athletes, id);
      return "<span class=\"permission-chip\" data-permission-athlete=\"" + athlete.id + "\"><span>" + escapeHtml(athleteLabel(athlete)) + "</span><button type=\"button\" aria-label=\"" + escapeHtml(t("Eliminar")) + "\" data-remove-permission=\"" + kind + "\" data-athlete-id=\"" + athlete.id + "\">&times;</button></span>";
    }).join("");
  }
  function renderUsers() { byId("users-body").innerHTML = state.users.map(function (u) { return "<tr><td>" + escapeHtml(u.name) + "</td><td>" + escapeHtml(u.username) + "</td><td>" + t(u.role === "admin" ? "Administrador" : (u.role === "marks_manager" ? "Gestor de marcas" : "Usuario normal")) + "</td><td>" + t(u.active ? "Activo" : "Inactivo") + "</td><td class=\"row-actions\"><button class=\"row-button\" data-edit-user=\"" + u.id + "\">" + t("Editar") + "</button><button class=\"row-button danger\" data-delete-user=\"" + u.id + "\">" + t("Eliminar") + "</button></td></tr>"; }).join(""); byId("users-empty").classList.toggle("hidden", state.users.length > 0); renderUserPermissions(byValue(state.users, byId("user-id").value)); }
  function filteredMarks() { var q = normalized(byId("marks-athlete-filter").value); if (!q) return []; var ids = state.athletes.filter(function (a) { return normalized(athleteLabel(a)).includes(q); }).map(function (a) { return String(a.id); }); return state.marks.filter(function (m) { return ids.includes(String(m.athleteId)); }); }
  function eventOptions(selected) { return state.events.slice().sort(compareEvents).map(function (e) { return "<option value=\"" + e.id + "\"" + (String(e.id) === String(selected) ? " selected" : "") + ">" + escapeHtml(eventLabel(e)) + "</option>"; }).join(""); }
  function markAuditTitle(mark) { var parts = []; if (mark.createdBy) parts.push(t("Entrada por") + ": " + mark.createdBy); if (mark.updatedBy) parts.push(t("Modificada por") + ": " + mark.updatedBy); return parts.join("\n"); }
  function renderMarks() { var rows = filteredMarks(); byId("marks-body").innerHTML = rows.map(function (m) { var e = byValue(state.events, m.eventId), c = byValue(state.cities, m.cityId), title = escapeHtml(markAuditTitle(m)), canEdit = canEditAthleteMarks(m.athleteId), edit = canEdit ? "<button class=\"row-button\" data-edit-mark=\"" + m.id + "\">" + t("Editar") + "</button>" : "", remove = canEdit ? "<button class=\"row-button danger\" data-delete-mark=\"" + m.id + "\">" + t("Eliminar") + "</button>" : ""; if (String(editingMarkId) === String(m.id)) return "<tr class=\"editing-row\"><td><select data-mark-event=\"" + m.id + "\">" + eventOptions(m.eventId) + "</select></td><td><input data-mark-result=\"" + m.id + "\" value=\"" + escapeHtml(normalizeResultText(m.result)) + "\"><input data-mark-technical=\"" + m.id + "\" value=\"" + escapeHtml(technicalValue(m.technicalInfo)) + "\" placeholder=\"" + escapeHtml(t("Marca técnica")) + "\"></td><td>" + escapeHtml(categoryLabel(m.category)) + "</td><td><input data-mark-date=\"" + m.id + "\" type=\"date\" value=\"" + escapeHtml(m.date) + "\"></td><td><input data-mark-city=\"" + m.id + "\" list=\"city-options\" value=\"" + escapeHtml(c ? cityLabel(c) : "") + "\"><div data-mark-track-wrap=\"" + m.id + "\">" + inlineTrackHtml(m.id, e ? e.area : "", c ? c.id : null, m.trackName || "") + "</div></td><td class=\"row-actions\"><button class=\"row-button\" data-save-mark=\"" + m.id + "\">" + t("Guardar") + "</button><button class=\"row-button\" data-cancel-inline-mark=\"1\">" + t("Cancelar") + "</button></td></tr>"; return "<tr><td>" + escapeHtml(e ? eventLabel(e) : "") + "</td><td title=\"" + title + "\">" + markResultCell(m) + "</td><td>" + escapeHtml(categoryLabel(m.category)) + "</td><td>" + formatDate(m.date) + "</td><td>" + escapeHtml(c ? cityLabel(c) : "") + detailLine(m.trackName, t("Instalación")) + "</td><td class=\"row-actions\">" + edit + remove + "</td></tr>"; }).join(""); byId("marks-empty").classList.toggle("hidden", rows.length > 0); }
  function renderDeletedMarks() { var rows=state.deletedMarks||[]; byId("deleted-marks-count").textContent=rows.length; byId("deleted-marks-body").innerHTML=rows.map(function(m){return "<tr><td>"+escapeHtml(m.athlete||"")+"</td><td>"+escapeHtml(eventLabel(m))+"</td><td>"+markResultCell(m)+"</td><td>"+formatDate(m.date)+"</td><td>"+escapeHtml((m.deletedAt||"")+(m.deletedBy?" - "+m.deletedBy:""))+"</td><td class=\"row-actions\"><button class=\"row-button\" data-restore-mark=\""+m.id+"\">Recuperar</button></td></tr>";}).join(""); byId("deleted-marks-empty").classList.toggle("hidden", rows.length>0); }
  function render() { renderOptions(); renderAthletes(); renderEvents(); renderCities(); renderTracks(); renderTranslations(); renderUsers(); renderMarks(); renderDeletedMarks(); byId("count-athletes").textContent = state.athletes.length; byId("count-events").textContent = state.events.length; byId("count-marks").textContent = state.marks.length; updateCategory(); updateReplaceFields(); }

  function reset(prefix) { byId(prefix + "-form").reset(); setError(prefix, ""); byId(prefix + "-id").value = ""; var cancel = byId("cancel-" + prefix); if (cancel) cancel.classList.add("hidden"); if (prefix === "mark") { byId("mark-date").value = today(); renderEventSelect(); updateCategory(); } if (prefix === "event") byId("event-direction").value = "lower"; if (prefix === "city") byId("delete-city").classList.add("hidden"); if (prefix === "track") { editingTrackId = null; byId("track-area").value = "pista_cubierta"; renderTracks(); } if (prefix === "user") { byId("user-password").required = true; byId("user-active").checked = true; byId("user-role").value = "normal"; renderUserPermissions(null); } }
  async function saveAthlete(e) { e.preventDefault(); var id = byId("athlete-id").value; try { await request("/athletes" + (id ? "/" + id : ""), { method: id ? "PUT" : "POST", body: JSON.stringify({ name: byId("athlete-name").value, surname: byId("athlete-surname").value, birthdate: byId("athlete-birthdate").value, sex: byId("athlete-sex").value }) }); reset("athlete"); await refresh(); } catch (error) { setError("athlete", error.message); } }
  async function moveAthleteMarks(e) { e.preventDefault(); var source=athleteFromInput("move-source-athlete"), target=athleteFromInput("move-target-athlete"); if(!source||!target){status("move-marks-status","Selecciona atleta origen y destino del listado.",true);return;} if(String(source.id)===String(target.id)){status("move-marks-status","El atleta origen y destino deben ser diferentes.",true);return;} try{var out=await request("/athletes/move-marks",{method:"POST",body:JSON.stringify({sourceAthleteId:source.id,targetAthleteId:target.id})});byId("move-marks-form").reset();await refresh();status("move-marks-status",out.moved+" marcas movidas a "+athleteLabel(target)+".",false);}catch(error){status("move-marks-status",error.message,true);} }
  async function saveEvent(e) { e.preventDefault(); var id = byId("event-id").value, payload = { area: byId("event-area").value, eventGroup: byId("event-group").value, name: byId("event-name").value, resultDirection: byId("event-direction").value, requiresTechnicalInfo: byId("event-technical").checked }; try { await request("/events" + (id ? "/" + id : ""), { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }); reset("event"); await refresh(); } catch (error) { setError("event", error.message); } }
  async function saveCity(e) { e.preventDefault(); var id=byId("city-id").value; try { await request("/cities" + (id ? "/" + id : ""), { method: id ? "PUT" : "POST", body: JSON.stringify({ name: byId("city-name").value, province: byId("city-province").value }) }); reset("city"); await refresh(); status("city-import-status", id ? "Ciudad actualizada." : "Ciudad creada.", false); } catch (error) { setError("city", error.message); } }
  async function saveMark(e) { e.preventDefault(); var athlete = selectedAthlete(), city = selectedCity(byId("mark-city").value), item = currentEvent(); if (!athlete || !city || !item) { setError("mark", "Selecciona un atleta, una prueba y una ciudad existentes."); return; } try { var id = byId("mark-id").value; await request("/marks" + (id ? "/" + id : ""), { method: id ? "PUT" : "POST", body: JSON.stringify({ athleteId: athlete.id, eventId: item.id, cityId: city.id, date: byId("mark-date").value, result: byId("mark-result").value, trackName: selectedTrackName(), technicalInfo: byId("mark-technical-info").value }) }); reset("mark"); await refresh(); } catch (error) { setError("mark", error.message); } }
  async function saveTrack(e) { e.preventDefault(); var id=byId("track-id").value, city=selectedCity(byId("track-city").value); if(!city){setError("track","Selecciona una ciudad existente.");return;} try { await request("/tracks" + (id ? "/" + id : ""), { method: id ? "PUT" : "POST", body: JSON.stringify({ area: byId("track-area").value, cityId: city.id, name: byId("track-name").value }) }); reset("track"); await refresh(); } catch (error) { setError("track", error.message); } }
  async function saveTranslation(e) { e.preventDefault(); var id = byId("translation-id").value; try { await request("/translations" + (id ? "/" + id : ""), { method: id ? "PUT" : "POST", body: JSON.stringify({ literal: byId("translation-literal").value, es: byId("translation-es").value, ca: byId("translation-ca").value }) }); reset("translation"); await refresh(); } catch (error) { setError("translation", error.message); } }
  async function changePassword(e) { e.preventDefault(); byId("password-status").classList.add("hidden"); setError("password", ""); try { await request("/auth/password", { method: "POST", body: JSON.stringify({ currentPassword: byId("password-current").value, newPassword: byId("password-new").value }) }); byId("password-form").reset(); status("password-status", "Contrasena actualizada.", false); } catch (error) { setError("password", error.message); } }
  function userPermissionsPayload() {
    var createIds = selectedPermissionIds("create"), editIds = selectedPermissionIds("edit"), ids = createIds.concat(editIds).filter(function (id, index, all) { return all.indexOf(id) === index; });
    return ids.map(function (id) { return { athleteId: id, canCreate: createIds.indexOf(id) !== -1, canEdit: editIds.indexOf(id) !== -1 }; });
  }
  async function saveUser(e) { e.preventDefault(); var id = byId("user-id").value, payload = { name: byId("user-name").value, username: byId("user-username").value, role: byId("user-role").value, active: byId("user-active").checked, permissions: userPermissionsPayload() }; if (!id || byId("user-password").value) payload.password = byId("user-password").value; try { await request("/users" + (id ? "/" + id : ""), { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }); reset("user"); await refresh(); } catch (error) { setError("user", error.message); } }
  async function remove(resource, id, prefix) { try { await request("/" + resource + "/" + id, { method: "DELETE" }); reset(prefix); await refresh(); } catch (error) { setError(prefix, error.message); } }
  async function restoreMark(id) { try { await request("/deleted-marks/" + id + "/restore", { method: "POST", body: "{}" }); await refresh(); status("replace-marks-status","Marca recuperada.",false); } catch (error) { status("replace-marks-status",error.message,true); } }
  async function purgeDeletedMarks() { try { var out=await request("/deleted-marks/purge", { method: "POST", body: "{}" }); await refresh(); status("replace-marks-status",out.purged+" marcas purgadas.",false); } catch (error) { status("replace-marks-status",error.message,true); } }
  async function saveInlineAthlete(id) { try { await request("/athletes/" + id, { method: "PUT", body: JSON.stringify({ name: document.querySelector("[data-athlete-name=\"" + id + "\"]").value, surname: document.querySelector("[data-athlete-surname=\"" + id + "\"]").value, birthdate: document.querySelector("[data-athlete-birthdate=\"" + id + "\"]").value, sex: document.querySelector("[data-athlete-sex=\"" + id + "\"]").value }) }); editingAthleteId = null; await refresh(); } catch (error) { setError("athlete", error.message); } }
  async function saveInlineMark(id) { var mark=byValue(state.marks,id), city=selectedCity(document.querySelector("[data-mark-city=\"" + id + "\"]").value); if(!city){status("replace-marks-status","Selecciona una ciudad existente.",true);return;} try { await request("/marks/" + id, { method: "PUT", body: JSON.stringify({ athleteId: mark.athleteId, eventId: document.querySelector("[data-mark-event=\"" + id + "\"]").value, cityId: city.id, date: document.querySelector("[data-mark-date=\"" + id + "\"]").value, result: normalizeResultText(document.querySelector("[data-mark-result=\"" + id + "\"]").value), trackName: inlineTrackValue(id), technicalInfo: document.querySelector("[data-mark-technical=\"" + id + "\"]").value }) }); editingMarkId = null; await refresh(); } catch (error) { status("replace-marks-status",error.message,true); } }
  async function saveInlineTrack(id) { var city=selectedCity(document.querySelector("[data-track-city=\"" + id + "\"]").value); if(!city){setError("track","Selecciona una ciudad existente.");return;} try { await request("/tracks/" + id, { method: "PUT", body: JSON.stringify({ area: document.querySelector("[data-track-area=\"" + id + "\"]").value, cityId: city.id, name: document.querySelector("[data-track-name=\"" + id + "\"]").value }) }); editingTrackId = null; await refresh(); } catch (error) { setError("track", error.message); } }
  function editAthlete(id) { editingAthleteId = id; renderAthletes(); switchPanel("atletas"); }
  function editEvent(id) { var x=byValue(state.events,id);byId("event-id").value=x.id;byId("event-area").value=x.area;byId("event-group").value=x.eventGroup;byId("event-name").value=x.name;byId("event-direction").value=x.resultDirection;byId("event-technical").checked=Boolean(Number(x.requiresTechnicalInfo));byId("cancel-event").classList.remove("hidden");switchPanel("pruebas"); }
  function editTranslation(literal) { var x=translationRows().find(function (row) { return row.literal === literal; }); if (!x) return; byId("translation-id").value=x.id || "";byId("translation-literal").value=x.literal;byId("translation-es").value=x.es;byId("translation-ca").value=x.ca;byId("cancel-translation").classList.remove("hidden");switchPanel("traducciones"); }
  function editCity(city) { byId("city-id").value=city.id;byId("city-search").value=cityLabel(city);byId("city-name").value=city.name;byId("city-province").value=city.province || "";byId("cancel-city").classList.remove("hidden");byId("delete-city").classList.remove("hidden"); }
  function editTrack(id) { editingTrackId = id; renderTracks(); switchPanel("ciudades"); }
  function editMark(id) { editingMarkId = id; renderMarks(); switchPanel("consulta-marcas"); }
  function viewAthleteMarks(id) { var athlete = byValue(state.athletes, id); if (!athlete) return; editingMarkId = null; byId("marks-athlete-filter").value = athleteLabel(athlete); renderMarks(); switchPanel("consulta-marcas"); }
  function editUser(id) { var x=byValue(state.users,id);byId("user-id").value=x.id;byId("user-name").value=x.name;byId("user-username").value=x.username;byId("user-password").value="";byId("user-password").required=false;byId("user-role").value=x.role || "normal";byId("user-active").checked=x.active;renderUserPermissions(x);byId("cancel-user").classList.remove("hidden");switchPanel("usuarios"); }
  function permissionAthleteFromInput(kind) {
    var value = normalized(byId(permissionInputId(kind)).value), matches;
    if (!value) return null;
    matches = state.athletes.filter(function (a) { return normalized(athleteLabel(a)) === value; });
    if (matches.length !== 1) matches = state.athletes.filter(function (a) { return normalized(athleteLabel(a)).indexOf(value) !== -1; });
    return matches.length === 1 ? matches[0] : null;
  }
  function addPermissionAthlete(kind) {
    var athlete = permissionAthleteFromInput(kind), ids;
    if (!athlete) return;
    ids = selectedPermissionIds(kind);
    if (ids.indexOf(String(athlete.id)) === -1) ids.push(String(athlete.id));
    renderPermissionList(kind, ids);
    byId(permissionInputId(kind)).value = "";
  }
  function removePermissionAthlete(kind, id) { renderPermissionList(kind, selectedPermissionIds(kind).filter(function (x) { return String(x) !== String(id); })); }

  function parseCsv(text) {
    var clean = text.replace(/^\uFEFF/, "");
    var header = clean.split(/\r?\n/, 1)[0];
    var delimiter = (header.match(/;/g) || []).length >= (header.match(/,/g) || []).length ? ";" : ",";
    var rows = [], row = [], field = "", quoted = false;
    for (var i = 0; i < clean.length; i += 1) {
      var character = clean[i];
      if (quoted) {
        if (character === '"' && clean[i + 1] === '"') { field += '"'; i += 1; }
        else if (character === '"') quoted = false;
        else field += character;
      } else if (character === '"') {
        quoted = true;
      } else if (character === delimiter) {
        row.push(field.trim());
        field = "";
      } else if (character === "\n" || character === "\r") {
        if (character === "\r" && clean[i + 1] === "\n") i += 1;
        row.push(field.trim());
        if (row.some(function (value) { return value !== ""; })) rows.push(row);
        row = [];
        field = "";
      } else {
        field += character;
      }
    }
    row.push(field.trim());
    if (row.some(function (value) { return value !== ""; })) rows.push(row);
    return rows;
  }
  function indexedRows(text) { var rows=parseCsv(text), keys=rows.shift().map(normalized); return rows.map(function(row){ var x={};keys.forEach(function(key,i){x[key]=row[i]||"";});return x;}); }
  function hasImportMarkData(row) { return Boolean(String(row.atleta || row.marca || row.fecha || row.data || row.prueba || row.prova || row["ambito / grupo"] || row["ambit / grup"] || row.ambito || row.ambit || row.grupo || row.grup).trim()); }
  function rowCity(row) { return row.ciudad || row.ciutat || ""; }
  function rowsWithLineNumbers(text) { return indexedRows(text).map(function(x,i){x._line=i+2;return x;}).filter(hasImportMarkData); }
  function athleteByLabel(value) { var key=normalized(value); return state.athletes.find(function(a){return normalized(athleteLabel(a))===key;}); }
  function suggestedAthleteParts(value) { var parts=String(value||"").trim().split(/\s+/); return {name:parts.shift()||"",surname:parts.join(" ")}; }
  function importScope(row) { var value=row["ambito / grupo"]||row["ambit / grup"];if(value){var parts=value.split(/\s*\/\s*/);return {area:parts.shift()||"",group:parts.join(" / ")};}return {area:row.ambito||row.ambit,group:row.grupo||row.grup}; }
  function eventFromImportRow(row) { var scope=importScope(row), test=row.prueba||row.prova;return state.events.find(function(e){return (normalized(areaLabel(e.area))===normalized(scope.area)||normalized(t(areaLabel(e.area)))===normalized(scope.area))&&(normalized(e.eventGroup)===normalized(scope.group)||normalized(t(e.eventGroup))===normalized(scope.group))&&(normalized(e.name)===normalized(test)||normalized(t(e.name))===normalized(test));}); }
  function duplicateImportMark(athleteId,eventId,date,result) { var normalizedResult=normalizeResultText(result);return state.marks.find(function(mark){return String(mark.athleteId)===String(athleteId)&&String(mark.eventId)===String(eventId)&&mark.date===date&&normalizeResultText(mark.result)===normalizedResult;}); }
  function importTrackControlHtml(prefix,index,event,city,current) {
    var tracks=event&&city&&event.area!=="ruta"?tracksFor(event.area,city.id):[], value=String(current||""), hasCurrent=tracks.some(function(track){return track.name===value;});
    if(!tracks.length)return "<input data-import-track=\""+prefix+"-"+index+"\" value=\""+escapeHtml(value)+"\" placeholder=\""+escapeHtml(t("Pista"))+"\">";
    return "<select data-import-track-select=\""+prefix+"-"+index+"\">"+tracks.map(function(track){return "<option value=\""+escapeHtml(track.name)+"\""+(track.name===value?" selected":"")+">"+escapeHtml(track.name)+"</option>";}).join("")+(value&&!hasCurrent?"<option value=\""+escapeHtml(value)+"\" selected>"+escapeHtml(value)+"</option>":"")+"<option value=\"__new__\">"+escapeHtml(t("Añadir nueva"))+"</option></select><input class=\""+(hasCurrent||!value?"hidden":"")+"\" data-import-track=\""+prefix+"-"+index+"\" value=\""+escapeHtml(value&&!hasCurrent?value:"")+"\" placeholder=\""+escapeHtml(t("Nombre de la pista de atletismo"))+"\">";
  }
  function importEventOptions(selected) { return "<option value=\"\""+(!selected?" selected":"")+">"+escapeHtml(t("Seleccionar"))+"</option>"+eventOptions(selected); }
  function importRowHtml(prefix,row,index,fallbackAthlete) {
    var event=eventFromImportRow(row), city=selectedCity(rowCity(row)), athlete=row.atleta||fallbackAthlete||"", tag=prefix+"-"+index;
    return "<div class=\"import-preview-row\" data-import-row=\""+tag+"\"><div class=\"import-preview-line\"><strong>Fila "+escapeHtml(row._line)+"</strong><span data-import-warnings=\""+tag+"\"></span></div><label>"+escapeHtml(t("Atleta"))+"<input data-import-athlete=\""+tag+"\" list=\"athlete-options\" value=\""+escapeHtml(athlete)+"\" placeholder=\""+escapeHtml(t("Buscar atleta..."))+"\"></label><label>"+escapeHtml(t("Prueba"))+"<select data-import-event=\""+tag+"\">"+importEventOptions(event?event.id:"")+"</select></label><label>"+escapeHtml(t("Marca"))+"<input data-import-result=\""+tag+"\" value=\""+escapeHtml(normalizeResultText(row.marca))+"\"></label><label>"+escapeHtml(t("Fecha"))+"<input data-import-date=\""+tag+"\" type=\"date\" value=\""+escapeHtml(row.fecha||row.data)+"\"></label><label>"+escapeHtml(t("Ciudad"))+"<input data-import-city=\""+tag+"\" list=\"city-options\" value=\""+escapeHtml(city?cityLabel(city):rowCity(row))+"\" placeholder=\""+escapeHtml(t("Buscar ciudad..."))+"\"></label><label>"+escapeHtml(t("Caracteristica tecnica"))+"<input data-import-technical=\""+tag+"\" value=\""+escapeHtml(row["caracteristica tecnica"]||"")+"\"></label><label class=\"import-track-field\">"+escapeHtml(t("Pista recomendada"))+"<span data-import-track-wrap=\""+tag+"\">"+importTrackControlHtml(prefix,index,event,city,row.pista)+"</span></label></div>";
  }
  function renderImportPreview(formId,bodyId,rows,fallbackAthlete,statusId,message) {
    var prefix=formId==="mark-import-review-form"?"single":"multi";
    byId(bodyId).innerHTML="<div class=\"import-preview-list\">"+rows.map(function(row,index){return importRowHtml(prefix,row,index,fallbackAthlete);}).join("")+"</div><section class=\"import-preview-missing\"><h4>"+escapeHtml(t("Atletas no encontrados"))+"</h4><p class=\"helper bulk-helper\">"+escapeHtml(t("Escoge un atleta existente en cada fila o completa aqui las altas nuevas antes de subir."))+"</p><div data-import-missing=\""+prefix+"\"></div></section>";
    byId(formId).classList.remove("hidden");
    updateImportPreviewWarnings(prefix);
    status(statusId,message,false);
  }
  function importPreviewRows(prefix) { return Array.prototype.map.call(document.querySelectorAll("[data-import-row^=\""+prefix+"-\"]"),function(row){var tag=row.dataset.importRow, event=byValue(state.events,document.querySelector("[data-import-event=\""+tag+"\"]").value), city=selectedCity(document.querySelector("[data-import-city=\""+tag+"\"]").value), select=document.querySelector("[data-import-track-select=\""+tag+"\"]"), input=document.querySelector("[data-import-track=\""+tag+"\"]");return {tag:tag,line:row.querySelector(".import-preview-line strong").textContent.replace(/\D+/g,""),athleteName:document.querySelector("[data-import-athlete=\""+tag+"\"]").value,event:event,city:city,result:document.querySelector("[data-import-result=\""+tag+"\"]").value,date:document.querySelector("[data-import-date=\""+tag+"\"]").value,technicalInfo:document.querySelector("[data-import-technical=\""+tag+"\"]").value,trackName:select&&select.value!=="__new__"?select.value:(input?input.value:"")};}); }
  function missingAthleteNames(prefix) { var seen={};return importPreviewRows(prefix).map(function(row){return row.athleteName.trim();}).filter(function(name){var key=normalized(name);if(!name||athleteByLabel(name)||seen[key])return false;seen[key]=true;return true;}); }
  function renderImportMissing(prefix) {
    var wrap=document.querySelector("[data-import-missing=\""+prefix+"\"]"), existing={};
    if(!wrap)return;
    wrap.querySelectorAll("[data-missing-original]").forEach(function(row){var key=row.dataset.missingOriginal;existing[key]={name:row.querySelector("[data-missing-name]").value,surname:row.querySelector("[data-missing-surname]").value,birthdate:row.querySelector("[data-missing-birthdate]").value,sex:row.querySelector("[data-missing-sex]").value};});
    wrap.innerHTML=missingAthleteNames(prefix).map(function(original){var key=normalized(original), p=existing[key]||suggestedAthleteParts(original);return "<div class=\"missing-athlete-row\" data-missing-original=\""+escapeHtml(key)+"\"><strong>"+escapeHtml(original)+"</strong><label>"+escapeHtml(t("Nombre"))+"<input data-missing-name value=\""+escapeHtml(p.name||"")+"\"></label><label>"+escapeHtml(t("Apellidos"))+"<input data-missing-surname value=\""+escapeHtml(p.surname||"")+"\"></label><label>"+escapeHtml(t("Fecha de nacimiento"))+"<input data-missing-birthdate type=\"date\" value=\""+escapeHtml(p.birthdate||"")+"\"></label><label>"+escapeHtml(t("Sexo"))+"<select data-missing-sex><option value=\"\">"+escapeHtml(t("Seleccionar"))+"</option><option value=\"femenino\""+(p.sex==="femenino"?" selected":"")+">"+escapeHtml(t("Femenino"))+"</option><option value=\"masculino\""+(p.sex==="masculino"?" selected":"")+">"+escapeHtml(t("Masculino"))+"</option></select></label></div>";}).join("");
    wrap.closest(".import-preview-missing").classList.toggle("hidden", !wrap.innerHTML);
  }
  function updateImportTrack(tag) {
    var event=byValue(state.events,document.querySelector("[data-import-event=\""+tag+"\"]").value), city=selectedCity(document.querySelector("[data-import-city=\""+tag+"\"]").value), wrap=document.querySelector("[data-import-track-wrap=\""+tag+"\"]"), select=document.querySelector("[data-import-track-select=\""+tag+"\"]"), input=document.querySelector("[data-import-track=\""+tag+"\"]"), value=select&&select.value!=="__new__"?select.value:(input?input.value:"");
    if(wrap)wrap.innerHTML=importTrackControlHtml(tag.split("-")[0],tag.split("-")[1],event,city,value);
  }
  function updateImportPreviewWarnings(prefix) {
    importPreviewRows(prefix).forEach(function(row){var athlete=athleteByLabel(row.athleteName), warnings=[], target=document.querySelector("[data-import-warnings=\""+row.tag+"\"]");if(!athlete)warnings.push("Atleta no encontrado");if(!row.event)warnings.push("Prueba no encontrada");if(!row.city)warnings.push("Ciudad no encontrada");if(athlete&&row.event&&row.date&&row.result&&duplicateImportMark(athlete.id,row.event.id,row.date,row.result))warnings.push("Posible duplicado");target.innerHTML=warnings.map(function(w){return "<span class=\"warning-chip\">"+escapeHtml(t(w))+"</span>";}).join("");});
    renderImportMissing(prefix);
  }
  async function createMissingAthletes(prefix) {
    var aliases={}, created=false, rows=Array.prototype.slice.call(document.querySelectorAll("[data-import-missing=\""+prefix+"\"] [data-missing-original]"));
    for(var i=0;i<rows.length;i++){var row=rows[i], name=row.querySelector("[data-missing-name]").value.trim(), surname=row.querySelector("[data-missing-surname]").value.trim(), birthdate=row.querySelector("[data-missing-birthdate]").value, sex=row.querySelector("[data-missing-sex]").value, label=(name+" "+surname).trim();if(!name||!surname||!birthdate||!sex)continue;await request("/athletes",{method:"POST",body:JSON.stringify({name:name,surname:surname,birthdate:birthdate,sex:sex})});aliases[row.dataset.missingOriginal]=label;created=true;}
    if(created)await refresh();
    return aliases;
  }
  async function submitImportPreview(prefix,statusId) {
    var aliases=await createMissingAthletes(prefix), errors=[], marks=[];
    importPreviewRows(prefix).forEach(function(row){var athlete=athleteByLabel(aliases[normalized(row.athleteName)]||row.athleteName);if(!athlete)errors.push("Fila "+row.line+": atleta no encontrado.");if(!row.event)errors.push("Fila "+row.line+": prueba no coincide con el catálogo.");if(!row.city)errors.push("Fila "+row.line+": ciudad no existe.");if(athlete&&row.event&&row.city)marks.push({athleteId:athlete.id,eventId:row.event.id,cityId:row.city.id,result:normalizeResultText(row.result),date:row.date,trackName:row.trackName,technicalInfo:row.technicalInfo,_line:Number(row.line)});});
    if(errors.length){status(statusId,errors.join(" "),true);return;}
    var out=await request("/marks/import/multiple",{method:"POST",body:JSON.stringify({marks:marks})});
    if(out.errors.length){status(statusId,out.errors.map(function(error){return "Fila "+error.row+": "+error.error;}).join(" "),true);return;}
    await refresh();
    byId(prefix==="single"?"mark-import-review-form":"multi-mark-import-review-form").classList.add("hidden");
    if(prefix==="single")pendingSingleMarks=[];else pendingMultiMarks=[];
    status(statusId,out.imported+" marcas importadas.",false);
  }
  function download(name, csv) { var link=document.createElement("a");link.href=URL.createObjectURL(new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"}));link.download=name;link.click();URL.revokeObjectURL(link.href); }
  function updateTemplateDownload(selectId, linkId, multi) {
    var format = byId(selectId).value, prefix = multi ? "plantilla-resultados-atletas" : "plantilla-resultados";
    var suffix = format === "microsoft2021" ? "microsoft-2021" : format === "microsoft" ? "microsoft" : "libreoffice";
    var extension = format === "microsoft2021" ? ".xlsm" : ".xlsx";
    var variant = format === "microsoft2021" ? "-microsoft-2021" : format === "microsoft" ? "-microsoft" : "";
    var version = format === "microsoft2021" ? "xlsm1" : format === "microsoft" ? "ms7" : "lo";
    byId(linkId).href = "../assets/" + prefix + variant + extension + "?v=20260528-" + version;
    byId(linkId).download = prefix + "-" + suffix + ".xlsx";
    if (format === "microsoft2021") byId(linkId).download = prefix + "-" + suffix + ".xlsm";
  }
  function downloadAthletesList() { var rows = ["Id;Nombre;Apellidos;Fecha de nacimiento;Sexo"].concat(state.athletes.map(function(a){return [a.id,a.name,a.surname,a.birthdate,a.sex].map(csvEscape).join(";");})); download("llistat-atletes.csv", rows.join("\n") + "\n"); }
  async function importAthletes(text) { var rows=indexedRows(text).map(function(x){return {id:x.id,name:x.nombre,surname:x.apellidos,birthdate:x["fecha de nacimiento"]||x.fecha_nacimiento,sex:normalized(x.sexo)==="femenino"?"femenino":"masculino"};});var out=await request("/athletes/import",{method:"POST",body:JSON.stringify({athletes:rows})});await refresh();status("athlete-import-status",out.imported+" atletas importados, "+(out.updated||0)+" actualizados, "+out.duplicates+" duplicados y "+out.invalid+" no válidos.",out.invalid>0); }
  async function importCities(text) { var rows=indexedRows(text).map(function(x){return {name:x.ciudad||x.nombre,province:x.provincia};});var out=await request("/cities/import",{method:"POST",body:JSON.stringify({cities:rows})});await refresh();status("city-import-status",out.imported+" ciudades importadas.",false); }
  async function mergeCities(e) { e.preventDefault(); var source=selectedCity(byId("merge-source-city").value), target=selectedCity(byId("merge-target-city").value); if(!source||!target){status("merge-cities-status","Selecciona ciudad origen y destino del listado.",true);return;} try{var out=await request("/cities/merge",{method:"POST",body:JSON.stringify({sourceCityId:source.id,targetCityId:target.id,area:byId("merge-area").value,year:byId("merge-year").value})});byId("merge-cities-form").reset();await refresh();status("merge-cities-status",out.updated+" marcas movidas y ciudad fusionada.",false);}catch(error){status("merge-cities-status",error.message,true);} }
  async function importMarks(text) { var athlete=selectedImportAthlete(), fallback=athlete?athleteLabel(athlete):byId("mark-import-athlete").value.trim();if(!fallback){status("mark-import-status","Indica el atleta al que corresponden las marcas.",true);return;}pendingSingleMarks=rowsWithLineNumbers(text);if(!pendingSingleMarks.length){status("mark-import-status","El archivo CSV esta vacio.",true);return;}renderImportPreview("mark-import-review-form","mark-import-review-body",pendingSingleMarks,fallback,"mark-import-status","Revisa y edita las marcas antes de subirlas."); }
  async function finishSingleMarksImport(e) { if(e)e.preventDefault();await submitImportPreview("single","mark-import-status"); }
  async function beginMultiMarksImport(text) { pendingMultiMarks=rowsWithLineNumbers(text).filter(function(x){return String(x.atleta||"").trim()!=="";});if(!pendingMultiMarks.length){status("multi-mark-import-status","El fichero no contiene la columna Atleta o no tiene filas.",true);return;}renderImportPreview("multi-mark-import-review-form","multi-mark-import-review-body",pendingMultiMarks,"","multi-mark-import-status","Revisa y edita las marcas antes de subirlas."); }
  async function continueMultiMarksImport(e) { if(e)e.preventDefault();await submitImportPreview("multi","multi-mark-import-status"); }
  async function finishMultiMarksImport(e) { if(e)e.preventDefault();await submitImportPreview("multi","multi-mark-import-status"); }
  function readFile(input, callback) { var file=input.files[0];if(!file)return;var reader=new FileReader();reader.onload=function(){callback(String(reader.result)).catch(function(error){status(input.id==="import-cities-file"?"city-import-status":input.id==="import-marks-file"?"mark-import-status":input.id==="import-multi-marks-file"?"multi-mark-import-status":"athlete-import-status",error.message,true);});input.value="";};reader.readAsText(file); }

  byId("mark-date").value=today();
  document.querySelector(".tabs").addEventListener("click",function(e){if(e.target.dataset.panel)switchPanel(e.target.dataset.panel);});
  byId("login-form").addEventListener("submit",function(e){e.preventDefault();request("/auth/login",{method:"POST",body:JSON.stringify({username:byId("login-username").value,password:byId("login-password").value})}).then(async function(x){showApplication(x.user);try { await refresh(); } catch (error) { return; }}).catch(function(error){setError("login",error.message);});});
  byId("setup-form").addEventListener("submit",function(e){e.preventDefault();request("/auth/setup",{method:"POST",body:JSON.stringify({name:byId("setup-name").value,username:byId("setup-username").value,password:byId("setup-password").value})}).then(async function(x){showApplication(x.user);try { await refresh(); } catch (error) { return; }}).catch(function(error){setError("setup",error.message);});});
  byId("logout").addEventListener("click",function(){request("/auth/logout",{method:"POST",body:"{}"}).then(function(){window.location.href="/";});});
  byId("athlete-form").addEventListener("submit",saveAthlete);byId("move-marks-form").addEventListener("submit",moveAthleteMarks);byId("event-form").addEventListener("submit",saveEvent);byId("city-form").addEventListener("submit",saveCity);byId("track-form").addEventListener("submit",saveTrack);byId("merge-cities-form").addEventListener("submit",mergeCities);byId("mark-form").addEventListener("submit",saveMark);byId("translation-form").addEventListener("submit",saveTranslation);byId("user-form").addEventListener("submit",saveUser);byId("password-form").addEventListener("submit",changePassword);
  ["athlete","event","mark","translation","user","city","track"].forEach(function(x){byId("cancel-"+x).addEventListener("click",function(){reset(x);});});
  byId("mark-area").addEventListener("change",function(){byId("mark-track-name").value="";renderEventSelect();});byId("mark-event").addEventListener("change",updateMarkFields);byId("mark-city").addEventListener("change",function(){byId("mark-track-name").value="";updateTrackChoices();});byId("mark-track-select").addEventListener("change",function(){var custom=this.value==="__new__";byId("track-name-field").classList.toggle("hidden",!custom);byId("mark-track-name").value=custom?"":this.value;});byId("mark-athlete").addEventListener("input",updateCategory);byId("mark-date").addEventListener("input",updateCategory);byId("marks-athlete-filter").addEventListener("input",renderMarks);
  byId("city-search").addEventListener("change",function(){var city=selectedCity(this.value); if(city) editCity(city); else { byId("city-id").value=""; byId("city-name").value=this.value; byId("city-province").value=""; byId("cancel-city").classList.remove("hidden"); byId("delete-city").classList.add("hidden"); }});
  byId("delete-city").addEventListener("click",function(){var id=byId("city-id").value;if(id)remove("cities",id,"city");});
  byId("user-role").addEventListener("change",function(){renderUserPermissions(byValue(state.users, byId("user-id").value));});
  ["create","edit"].forEach(function(kind){byId(permissionInputId(kind)).addEventListener("change",function(){addPermissionAthlete(kind);});byId(permissionInputId(kind)).addEventListener("keydown",function(e){if(e.key==="Enter"){e.preventDefault();addPermissionAthlete(kind);}});});
  byId("add-import-athlete").addEventListener("click",function(){ var parts=byId("mark-import-athlete").value.trim().split(/\s+/); reset("athlete"); if(parts.length){byId("athlete-name").value=parts.shift();byId("athlete-surname").value=parts.join(" ");} switchPanel("atletas"); });
  byId("download-athlete-template").addEventListener("click",function(){download("plantilla-atletas.csv","Nombre;Apellidos;Fecha de nacimiento;Sexo\nAnna;Garcia Lopez;2010-05-18;femenino\n");});
  byId("download-athletes-list").addEventListener("click",downloadAthletesList);
  byId("results-template-format").addEventListener("change",function(){updateTemplateDownload("results-template-format","download-results-template",false);});
  byId("multi-results-template-format").addEventListener("change",function(){updateTemplateDownload("multi-results-template-format","download-multi-results-template",true);});
  byId("replace-field").addEventListener("change",function(){byId("replace-search").value="";byId("replace-value").value="";byId("replace-city").value="";byId("replace-area").value="";byId("replace-year").value="";updateReplaceFields();});
  byId("replace-marks-form").addEventListener("submit",function(e){e.preventDefault();var payload={field:byId("replace-field").value,search:byId("replace-search").value,replace:byId("replace-value").value,area:byId("replace-area").value,year:byId("replace-year").value};if(payload.field==="city"){var source=selectedCity(payload.search), target=selectedCity(payload.replace);if(!source||!target){status("replace-marks-status","Selecciona la ciudad a reemplazar y la ciudad nueva del listado.",true);return;}payload.searchCityId=source.id;payload.replaceCityId=target.id;}else{var filterCityValue=byId("replace-city").value.trim();if(filterCityValue){var filterCity=selectedCity(filterCityValue);if(!filterCity){status("replace-marks-status","Selecciona una ciudad existente para filtrar.",true);return;}payload.cityId=filterCity.id;}}request("/marks/replace",{method:"POST",body:JSON.stringify(payload)}).then(async function(out){await refresh();status("replace-marks-status",out.updated+" marcas actualizadas.",false);}).catch(function(error){status("replace-marks-status",error.message,true);});});
  byId("purge-deleted-marks").addEventListener("click",purgeDeletedMarks);
  byId("mark-import-review-form").addEventListener("submit",function(e){finishSingleMarksImport(e).catch(function(error){status("mark-import-status",error.message,true);});});
  byId("multi-mark-import-review-form").addEventListener("submit",function(e){continueMultiMarksImport(e).catch(function(error){status("multi-mark-import-status",error.message,true);});});
  byId("missing-athletes-form").addEventListener("submit",function(e){finishMultiMarksImport(e).catch(function(error){status("multi-mark-import-status",error.message,true);});});
  byId("import-athletes-file").addEventListener("change",function(){readFile(this,importAthletes);});byId("import-cities-file").addEventListener("change",function(){readFile(this,importCities);});byId("import-marks-file").addEventListener("change",function(){readFile(this,importMarks);});byId("import-multi-marks-file").addEventListener("change",function(){readFile(this,beginMultiMarksImport);});
  document.body.addEventListener("change",function(e){var d=e.target.dataset;if(d.markCity||d.markEvent)updateInlineMarkTrack(d.markCity||d.markEvent);if(d.markTrackSelect){var custom=e.target.value==="__new__", input=document.querySelector("[data-mark-track=\"" + d.markTrackSelect + "\"]");if(input){input.classList.toggle("hidden",!custom);if(!custom)input.value=e.target.value;}}if(d.importEvent||d.importCity){updateImportTrack(d.importEvent||d.importCity);updateImportPreviewWarnings((d.importEvent||d.importCity).split("-")[0]);}if(d.importTrackSelect){var importCustom=e.target.value==="__new__", importInput=document.querySelector("[data-import-track=\"" + d.importTrackSelect + "\"]");if(importInput){importInput.classList.toggle("hidden",!importCustom);if(!importCustom)importInput.value=e.target.value;}}if(d.importAthlete||d.importResult||d.importDate||d.importTrack||d.importTrackSelect||d.importTechnical)updateImportPreviewWarnings((d.importAthlete||d.importResult||d.importDate||d.importTrack||d.importTrackSelect||d.importTechnical).split("-")[0]);});
  document.body.addEventListener("input",function(e){var d=e.target.dataset, tag=d.importAthlete||d.importResult||d.importDate||d.importCity||d.importTrack||d.importTechnical;if(tag)updateImportPreviewWarnings(tag.split("-")[0]);});
  document.body.addEventListener("click",function(e){var d=e.target.dataset;if(d.removePermission){removePermissionAthlete(d.removePermission,d.athleteId);return;}if(d.viewAthleteMarks){viewAthleteMarks(d.viewAthleteMarks);return;}if(d.editAthlete)editAthlete(d.editAthlete);if(d.saveAthlete)saveInlineAthlete(d.saveAthlete);if(d.cancelInlineAthlete){editingAthleteId=null;renderAthletes();}if(d.editEvent)editEvent(d.editEvent);if(d.editTrack)editTrack(d.editTrack);if(d.saveTrack)saveInlineTrack(d.saveTrack);if(d.cancelInlineTrack){editingTrackId=null;renderTracks();}if(d.editTranslationLiteral)editTranslation(decodeURIComponent(d.editTranslationLiteral));if(d.editMark)editMark(d.editMark);if(d.restoreMark)restoreMark(d.restoreMark);if(d.saveMark)saveInlineMark(d.saveMark);if(d.cancelInlineMark){editingMarkId=null;renderMarks();}if(d.editUser)editUser(d.editUser);if(d.deleteAthlete)remove("athletes",d.deleteAthlete,"athlete");if(d.deleteEvent)remove("events",d.deleteEvent,"event");if(d.deleteTrack)remove("tracks",d.deleteTrack,"track");if(d.deleteTranslation)remove("translations",d.deleteTranslation,"translation");if(d.deleteMark)remove("marks",d.deleteMark,"mark");if(d.deleteUser)remove("users",d.deleteUser,"user");});
  document.addEventListener("rankinglanguagechange",render);
  initialize();
}());
