<?php
declare(strict_types=1);

require_once dirname(__DIR__) . '/lib/env.php';

session_name('ranking_session');
session_set_cookie_params(['httponly' => true, 'samesite' => 'Strict', 'secure' => !empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off', 'path' => '/']);
session_start();

const EVENT_AREAS = ['pista_cubierta', 'aire_libre', 'ruta'];
const EVENT_CATALOGUE = [
    'pista_cubierta' => [
        'Curses' => ['60', '80', '100', '120', '150', '200', '300', '400', '600', '800', '1000', '1500', 'Milla', '2000', '3000', '5000', '10000'],
        'Tanques' => ['60 mt', '80 mt', '100 mt', '110 mt', '220 mt', '300 mt', '400 mt'],
        'Relleus' => ['4x60', '4x80', '4x100', '4x200', '4x300', '4x400', '3x600'],
        'Obstacles' => ['1000 sense ria', '1500', '2000', '3000'],
        'Salts' => ['Llargada', 'Triple', 'Alçada', 'Perxa'],
        'Llançaments' => ['Pes', 'Disc', 'Javelina', 'Martell', 'Martell pesat'],
        'Marxa' => ['1000', '2000', '3000', '5000', '10000'],
    ],
    'aire_libre' => [],
    'ruta' => [
        'Curses' => ['Milla', '5km', '10km', 'Mitja marató', 'Marató'],
        'Marxa' => ['1km', '2km', '3km', '5km', '10km', 'Mitja marató', 'Marató'],
    ],
];

final class ApiException extends RuntimeException { public function __construct(string $message, public readonly int $status = 400) { parent::__construct($message); } }
function respond(array $payload, int $status = 200): never { http_response_code($status); header('Content-Type: application/json; charset=utf-8'); header('Cache-Control: no-store, no-cache, must-revalidate'); header('Pragma: no-cache'); header('Expires: 0'); echo json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR); exit; }
function connection(): PDO { return databaseConnection(dirname(__DIR__, 2) . '/.env'); }
function execute(PDO $db, string $sql, array $parameters = []): PDOStatement { $statement = $db->prepare($sql); $statement->execute($parameters); return $statement; }
function input(): array { $content = file_get_contents('php://input'); if (!$content) return []; try { $data = json_decode($content, true, flags: JSON_THROW_ON_ERROR); } catch (JsonException) { throw new ApiException('La peticion contiene JSON no valido.'); } if (!is_array($data)) throw new ApiException('La peticion contiene JSON no valido.'); return $data; }
function path(): string { $uri = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) ?: ''; $position = strpos($uri, '/api'); return $position === false ? '/' : (substr($uri, $position + 4) ?: '/'); }
function requiredText(array $payload, string $key, string $label): string { $value = trim((string) ($payload[$key] ?? '')); if ($value === '') throw new ApiException("El campo {$label} es obligatorio."); return $value; }
function optionalText(array $payload, string $key): ?string { $value = trim((string) ($payload[$key] ?? '')); return $value === '' ? null : $value; }
function requiredId(array $payload, string $key, string $label): int { $id = filter_var($payload[$key] ?? null, FILTER_VALIDATE_INT, ['options' => ['min_range' => 1]]); if (!$id) throw new ApiException("El campo {$label} no es valido."); return (int) $id; }
function requiredDate(array $payload, string $key, string $label): string { $value = requiredText($payload, $key, $label); $year=$month=$day=null; if (preg_match('/^(\d{4})([-\/])(\d{1,2})\2(\d{1,2})$/', $value, $parts)) { $year=(int)$parts[1];$month=(int)$parts[3];$day=(int)$parts[4]; } elseif (preg_match('/^(\d{1,2})([-\/])(\d{1,2})\2(\d{2}|\d{4})$/', $value, $parts)) { $day=(int)$parts[1];$month=(int)$parts[3];$year=(int)$parts[4];if(strlen($parts[4])===2)$year+=($year>=70?1900:2000); } if ($year===null || !checkdate($month, $day, $year)) throw new ApiException("El campo {$label} debe tener un formato de fecha valido, por ejemplo AAAA-MM-DD, DD/MM/AAAA o D/M/AA."); $date=new DateTimeImmutable(sprintf('%04d-%02d-%02d',$year,$month,$day)); if ($date > new DateTimeImmutable('today')) throw new ApiException("El campo {$label} no puede estar en el futuro."); return $date->format('Y-m-d'); }
function titleCaseName(string $value): string { $value = preg_replace('/\s+/u', ' ', trim($value)) ?? trim($value); if (function_exists('mb_convert_case')) return mb_convert_case($value, MB_CASE_TITLE, 'UTF-8'); return ucwords(strtolower($value), " -'"); }
function normalizeAthleteNames(PDO $db): void { foreach (execute($db, 'SELECT id, nombre, apellidos FROM atletas')->fetchAll() as $athlete) { $name = titleCaseName($athlete['nombre']); $surname = titleCaseName($athlete['apellidos']); if ($name !== $athlete['nombre'] || $surname !== $athlete['apellidos']) execute($db, 'UPDATE atletas SET nombre = ?, apellidos = ? WHERE id = ?', [$name, $surname, $athlete['id']]); } }
function requiredSex(array $payload): string { $sex = (string) ($payload['sex'] ?? ''); if (!in_array($sex, ['masculino', 'femenino'], true)) throw new ApiException('Indica el sexo del atleta.'); return $sex; }
function normalizeResultText(string $value): string { $value = trim($value); if (preg_match('/^(\d+)[hH](\d{1,2})[\'’](\d{1,2})"(\d{0,2})$/', $value, $parts)) return sprintf('%d:%02d:%02d.%02d', (int) $parts[1], (int) $parts[2], (int) $parts[3], (int) str_pad($parts[4] !== '' ? $parts[4] : '0', 2, '0')); if (preg_match('/^(\d+)[\'’](\d{1,2})"(\d{0,2})$/', $value, $parts)) return sprintf('%d:%02d.%02d', (int) $parts[1], (int) $parts[2], (int) str_pad($parts[3] !== '' ? $parts[3] : '0', 2, '0')); if (preg_match('/^(\d+)"(\d{1,2})"$/', $value, $parts)) return ((int) $parts[1]) . ':' . str_pad((string) ((int) $parts[2]), 2, '0', STR_PAD_LEFT) . '.00'; if (preg_match('/^(\d+)"(\d{1,2})$/', $value, $parts)) return '00:' . str_pad((string) ((int) $parts[1]), 2, '0', STR_PAD_LEFT) . '.' . $parts[2]; if (preg_match('/^\d+,\d+$/', $value)) return str_replace(',', '.', $value); return $value; }
function requiredResult(array $payload): string { $value = normalizeResultText(requiredText($payload, 'result', 'marca')); $clean = preg_replace('/[^\d:.,]/', '', $value); if (!$clean || !preg_match('/^(?:\d+(?:[.,]\d+)?|(?:\d+:){1,2}\d+(?:[.,]\d+)?)$/', $clean)) throw new ApiException('Indica una marca numerica, por ejemplo 12.43 o 1:58.20.'); return $value; }
function resultDirection(array $payload): string { $value = (string) ($payload['resultDirection'] ?? 'lower'); if (!in_array($value, ['lower', 'higher'], true)) throw new ApiException('Indica el criterio de ranking.'); return $value === 'higher' ? 'mayor' : 'menor'; }
function eventArea(array $payload): string { $area = (string) ($payload['area'] ?? ''); if (!in_array($area, EVENT_AREAS, true)) throw new ApiException('Indica el ambito de la prueba.'); return $area; }
function ensureExists(PDO $db, string $table, int $id): void { if (!execute($db, "SELECT id FROM {$table} WHERE id = ?", [$id])->fetch()) throw new ApiException('El registro no existe.', 404); }
function comparableResult(string $result): float { $result = normalizeResultText($result); $parts = array_map('floatval', explode(':', str_replace(',', '.', preg_replace('/[^\d:,.]/', '', $result) ?? ''))); return match (count($parts)) { 3 => $parts[0] * 3600 + $parts[1] * 60 + $parts[2], 2 => $parts[0] * 60 + $parts[1], default => $parts[0] }; }
function categoryForDates(string $birthdate, string $date, string $sex): string {
    $birth = new DateTimeImmutable($birthdate);
    $performance = new DateTimeImmutable($date);
    if ($performance < $birth) throw new ApiException('La fecha de la marca no puede ser anterior al nacimiento.');
    $exactAge = $birth->diff($performance)->y;
    $calendarAge = (int) $performance->format('Y') - (int) $birth->format('Y');
    $base = match (true) {
        $exactAge >= 35 => 'Master ' . min(100, intdiv($exactAge, 5) * 5),
        $calendarAge < 8 => 'Sub8',
        $calendarAge < 10 => 'Sub10',
        $calendarAge < 12 => 'Sub12',
        $calendarAge < 14 => 'Sub14',
        $calendarAge < 16 => 'Sub16',
        $calendarAge < 18 => 'Sub18',
        $calendarAge < 20 => 'Sub20',
        $calendarAge < 23 => 'Sub23',
        default => 'Senior',
    };
    return $base . ' - ' . ($sex === 'femenino' ? 'Femenino' : 'Masculino');
}
function refreshCategories(PDO $db): void { foreach (execute($db, 'SELECT m.id, m.fecha, m.categoria, a.fecha_nacimiento, a.sexo FROM marcas m JOIN atletas a ON a.id=m.atleta_id')->fetchAll() as $mark) { $category = categoryForDates($mark['fecha_nacimiento'], $mark['fecha'], $mark['sexo']); if ($category !== $mark['categoria']) execute($db, 'UPDATE marcas SET categoria=? WHERE id=?', [$category, $mark['id']]); } }
function currentUser(PDO $db): ?array { if (empty($_SESSION['user_id'])) return null; $user = execute($db, "SELECT id, nombre AS name, usuario AS username, activo AS active, rol AS role FROM usuarios WHERE id = ? AND activo = 1", [(int) $_SESSION['user_id']])->fetch(); if (!$user) { unset($_SESSION['user_id']); return null; } $user['active'] = (bool) $user['active']; return $user; }
function requireUser(PDO $db): array { $user = currentUser($db); if (!$user) throw new ApiException('Debes iniciar sesion para continuar.', 401); return $user; }
function isAdmin(array $user): bool { return ($user['role'] ?? 'normal') === 'admin'; }
function hasGlobalMarkAccess(array $user): bool { return isAdmin($user) || ($user['role'] ?? 'normal') === 'marks_manager'; }
function requireAdmin(array $user): void { if (!isAdmin($user)) throw new ApiException('No tienes permisos para acceder a este apartado.', 403); }
function requireGlobalMarkAccess(array $user): void { if (!hasGlobalMarkAccess($user)) throw new ApiException('No tienes permisos para acceder a este apartado.', 403); }
function requiredUsername(array $payload): string { $username = strtolower(requiredText($payload, 'username', 'usuario')); if (!preg_match('/^[a-z0-9._-]{3,100}$/', $username)) throw new ApiException('El usuario no es valido.'); return $username; }
function requiredPassword(array $payload, bool $optional = false): ?string { $password = (string) ($payload['password'] ?? ''); if ($optional && $password === '') return null; if (strlen($password) < 8) throw new ApiException('La contrasena debe tener al menos 8 caracteres.'); return $password; }
function userRole(array $payload, bool $forceAdmin = false): string { if ($forceAdmin) return 'admin'; $role = (string) ($payload['role'] ?? 'normal'); if (!in_array($role, ['admin', 'normal', 'marks_manager'], true)) throw new ApiException('Indica un tipo de usuario valido.'); return $role; }
function userPermissions(PDO $db, int $userId): array { $rows = execute($db, 'SELECT atleta_id AS athleteId, puede_crear AS canCreate, puede_editar AS canEdit FROM usuario_atleta_permisos WHERE usuario_id = ? ORDER BY atleta_id', [$userId])->fetchAll(); foreach ($rows as &$row) { $row['canCreate'] = (bool) $row['canCreate']; $row['canEdit'] = (bool) $row['canEdit']; } return $rows; }
function saveUserPermissions(PDO $db, int $userId, string $role, array $payload): void { execute($db, 'DELETE FROM usuario_atleta_permisos WHERE usuario_id = ?', [$userId]); if ($role === 'admin' || $role === 'marks_manager') return; $permissions = $payload['permissions'] ?? []; if (!is_array($permissions)) throw new ApiException('Los permisos del usuario no son validos.'); $statement = $db->prepare('INSERT INTO usuario_atleta_permisos (usuario_id, atleta_id, puede_crear, puede_editar) VALUES (?, ?, ?, ?)'); foreach ($permissions as $permission) { if (!is_array($permission)) continue; $athleteId = filter_var($permission['athleteId'] ?? null, FILTER_VALIDATE_INT, ['options' => ['min_range' => 1]]); if (!$athleteId) continue; ensureExists($db, 'atletas', (int) $athleteId); $canCreate = !empty($permission['canCreate']); $canEdit = !empty($permission['canEdit']); if (!$canCreate && !$canEdit) continue; $statement->execute([$userId, (int) $athleteId, $canCreate ? 1 : 0, $canEdit ? 1 : 0]); } }
function users(PDO $db): array { $rows = execute($db, 'SELECT id, nombre AS name, usuario AS username, activo AS active, rol AS role FROM usuarios ORDER BY nombre')->fetchAll(); foreach ($rows as &$row) { $row['active'] = (bool) $row['active']; $row['permissions'] = userPermissions($db, (int) $row['id']); } return $rows; }
function createUser(PDO $db, array $payload, bool $force = false): int { $role = userRole($payload, $force); execute($db, 'INSERT INTO usuarios (nombre, usuario, password_hash, activo, rol) VALUES (?, ?, ?, ?, ?)', [requiredText($payload, 'name', 'nombre'), requiredUsername($payload), password_hash((string) requiredPassword($payload), PASSWORD_DEFAULT), ($force || !array_key_exists('active', $payload) || $payload['active']) ? 1 : 0, $role]); $id = (int) $db->lastInsertId(); saveUserPermissions($db, $id, $role, $payload); return $id; }
function activeAdminCount(PDO $db): int { return (int) execute($db, "SELECT COUNT(*) FROM usuarios WHERE activo = 1 AND rol = 'admin'")->fetchColumn(); }
function updateUser(PDO $db, int $id, array $payload, array $actor): void { $current = execute($db, 'SELECT activo, rol FROM usuarios WHERE id = ?', [$id])->fetch(); if (!$current) throw new ApiException('El registro no existe.', 404); $active = !array_key_exists('active', $payload) || (bool) $payload['active']; $role = userRole($payload); if ($id === (int) $actor['id'] && (!$active || $role !== 'admin')) throw new ApiException('No puedes quitarte tus propios permisos de administrador.'); if ((bool)$current['activo'] && $current['rol'] === 'admin' && (!$active || $role !== 'admin') && activeAdminCount($db) <= 1) throw new ApiException('Debe existir al menos un administrador activo.'); $params = [requiredText($payload, 'name', 'nombre'), requiredUsername($payload), $active ? 1 : 0, $role]; $sql = 'UPDATE usuarios SET nombre = ?, usuario = ?, activo = ?, rol = ?'; $password = requiredPassword($payload, true); if ($password !== null) { $sql .= ', password_hash = ?'; $params[] = password_hash($password, PASSWORD_DEFAULT); } $sql .= ' WHERE id = ?'; $params[] = $id; execute($db, $sql, $params); saveUserPermissions($db, $id, $role, $payload); }
function deleteUser(PDO $db, int $id, array $actor): void { if ($id === (int) $actor['id']) throw new ApiException('No puedes eliminar tu propio usuario.'); $current = execute($db, 'SELECT activo, rol FROM usuarios WHERE id = ?', [$id])->fetch(); if (!$current) throw new ApiException('El registro no existe.', 404); if ((bool)$current['activo'] && $current['rol'] === 'admin' && activeAdminCount($db) <= 1) throw new ApiException('Debe existir al menos un administrador activo.'); execute($db, 'DELETE FROM usuarios WHERE id = ?', [$id]); }
function changePassword(PDO $db, array $payload, array $actor): void { $current = execute($db, 'SELECT password_hash FROM usuarios WHERE id = ?', [(int)$actor['id']])->fetch(); if (!$current || !password_verify((string)($payload['currentPassword'] ?? ''), $current['password_hash'])) throw new ApiException('La contrasena actual no es correcta.', 403); execute($db, 'UPDATE usuarios SET password_hash = ? WHERE id = ?', [password_hash((string) requiredPassword(['password' => ($payload['newPassword'] ?? '')]), PASSWORD_DEFAULT), (int)$actor['id']]); }

function writeEvent(PDO $db, array $payload, ?int $id = null): void { $values = [requiredText($payload, 'name', 'prueba'), eventArea($payload), requiredText($payload, 'eventGroup', 'grupo'), resultDirection($payload), !empty($payload['requiresTechnicalInfo']) ? 1 : 0]; if ($id === null) { execute($db, 'INSERT INTO pruebas (nombre, ambito, grupo, sentido_resultado, informacion_adicional) VALUES (?, ?, ?, ?, ?)', $values); return; } ensureExists($db, 'pruebas', $id); $values[] = $id; execute($db, 'UPDATE pruebas SET nombre=?, ambito=?, grupo=?, sentido_resultado=?, informacion_adicional=? WHERE id=?', $values); }
function seedCatalogue(PDO $db): void {
    $catalogue = EVENT_CATALOGUE; $catalogue['aire_libre'] = $catalogue['pista_cubierta'];
    $statement = $db->prepare('INSERT IGNORE INTO pruebas (nombre, ambito, grupo, sentido_resultado, informacion_adicional) VALUES (?, ?, ?, ?, ?)');
    foreach ($catalogue as $area => $groups) foreach ($groups as $group => $names) foreach ($names as $name) {
        $higher = in_array($group, ['Salts', 'Llançaments'], true); $extra = in_array($group, ['Tanques', 'Llançaments'], true);
        $statement->execute([$name, $area, $group, $higher ? 'mayor' : 'menor', $extra ? 1 : 0]);
    }
}
function eventOrderSql(): string { return "FIELD(p.ambito, 'pista_cubierta', 'aire_libre', 'ruta'), p.grupo, CASE WHEN p.grupo IN ('Curses','Tanques') THEN CASE WHEN p.nombre = 'Milla' THEN 1609 WHEN p.nombre = 'Mitja marató' THEN 21097 WHEN p.nombre = 'Marató' THEN 42195 WHEN p.nombre LIKE '%km' THEN CAST(REPLACE(p.nombre, ',', '.') AS DECIMAL(10,2)) * 1000 ELSE CAST(REPLACE(p.nombre, ',', '.') AS DECIMAL(10,2)) END ELSE NULL END, p.nombre"; }
function events(PDO $db, bool $onlyWithMarks = false): array { $join = $onlyWithMarks ? ' JOIN marcas m ON m.prueba_id = p.id' : ''; return execute($db, "SELECT DISTINCT p.id, p.nombre AS name, p.ambito AS area, p.grupo AS eventGroup, p.informacion_adicional AS requiresTechnicalInfo, CASE p.sentido_resultado WHEN 'mayor' THEN 'higher' ELSE 'lower' END AS resultDirection FROM pruebas p{$join} ORDER BY " . eventOrderSql())->fetchAll(); }
function seedCities(PDO $db): void { if ((int) execute($db, 'SELECT COUNT(*) FROM ciudades')->fetchColumn() >= 8000) return; $handle = fopen(dirname(__DIR__) . '/database/ciudades_es.csv', 'rb'); if (!$handle) throw new RuntimeException('No se encuentra el catalogo de ciudades.'); fgetcsv($handle, separator: ';'); $statement = $db->prepare('INSERT IGNORE INTO ciudades (nombre, provincia) VALUES (?, ?)'); while (($row = fgetcsv($handle, separator: ';')) !== false) { if (count($row) >= 2 && trim($row[0]) !== '') $statement->execute([trim($row[0]), trim($row[1])]); } fclose($handle); }
function cities(PDO $db): array { return execute($db, 'SELECT id, nombre AS name, provincia AS province FROM ciudades ORDER BY nombre, provincia')->fetchAll(); }
function cityPayload(array $payload): array { return [requiredText($payload, 'name', 'ciudad'), trim((string)($payload['province'] ?? ''))]; }
function writeCity(PDO $db, array $payload, ?int $id = null): void { $values = cityPayload($payload); if ($id === null) { execute($db, 'INSERT INTO ciudades (nombre, provincia) VALUES (?, ?)', $values); return; } ensureExists($db, 'ciudades', $id); $values[] = $id; execute($db, 'UPDATE ciudades SET nombre = ?, provincia = ? WHERE id = ?', $values); }
function mergeCities(PDO $db, array $payload): array { $sourceId = requiredId($payload, 'sourceCityId', 'ciudad origen'); $targetId = requiredId($payload, 'targetCityId', 'ciudad destino'); if ($sourceId === $targetId) throw new ApiException('La ciudad origen y destino deben ser diferentes.'); ensureExists($db, 'ciudades', $sourceId); ensureExists($db, 'ciudades', $targetId); $statement = $db->prepare('UPDATE marcas SET ciudad_id = ? WHERE ciudad_id = ?'); $statement->execute([$targetId, $sourceId]); $updated = $statement->rowCount(); execute($db, 'DELETE FROM ciudades WHERE id = ?', [$sourceId]); return ['updated' => $updated]; }
function translations(PDO $db): array { return execute($db, 'SELECT id, literal AS literal, castellano AS es, catalan AS ca FROM traducciones ORDER BY literal')->fetchAll(); }
function locationSql(): string { return "COALESCE(c.nombre, t.localidad, '') AS city, COALESCE(m.nombre_pista, t.nombre, '') AS trackName, m.caracteristica_tecnica AS technicalInfo"; }
function marksSelect(): string { return "SELECT m.id, m.atleta_id AS athleteId, m.prueba_id AS eventId, m.ciudad_id AS cityId, m.nombre_pista AS trackName, m.caracteristica_tecnica AS technicalInfo, DATE_FORMAT(m.fecha, '%Y-%m-%d') AS date, m.resultado AS result, m.categoria AS category, creator.nombre AS createdBy, updater.nombre AS updatedBy FROM marcas m LEFT JOIN usuarios creator ON creator.id=m.creado_por LEFT JOIN usuarios updater ON updater.id=m.actualizado_por"; }
function permittedAthleteIds(PDO $db, array $user, string $action = 'any'): array { if (hasGlobalMarkAccess($user)) return []; $column = $action === 'edit' ? 'puede_editar' : ($action === 'create' ? 'puede_crear' : null); $sql = 'SELECT atleta_id FROM usuario_atleta_permisos WHERE usuario_id = ?'; if ($column) $sql .= " AND {$column} = 1"; return array_map('intval', execute($db, $sql, [(int) $user['id']])->fetchAll(PDO::FETCH_COLUMN)); }
function canAccessAthlete(PDO $db, array $user, int $athleteId, string $action): bool { if (hasGlobalMarkAccess($user)) return true; $column = $action === 'edit' ? 'puede_editar' : 'puede_crear'; return (bool) execute($db, "SELECT 1 FROM usuario_atleta_permisos WHERE usuario_id = ? AND atleta_id = ? AND {$column} = 1", [(int) $user['id'], $athleteId])->fetchColumn(); }
function requireAthletePermission(PDO $db, array $user, int $athleteId, string $action): void { if (!canAccessAthlete($db, $user, $athleteId, $action)) throw new ApiException('No tienes permisos sobre este atleta.', 403); }
function requireAnyAthletePermission(PDO $db, array $user, int $athleteId): void { if (isAdmin($user)) return; if (!execute($db, 'SELECT 1 FROM usuario_atleta_permisos WHERE usuario_id = ? AND atleta_id = ?', [(int)$user['id'], $athleteId])->fetchColumn()) throw new ApiException('No tienes permisos sobre este atleta.', 403); }
function markAthleteId(PDO $db, int $markId): int { $id = execute($db, 'SELECT atleta_id FROM marcas WHERE id = ?', [$markId])->fetchColumn(); if (!$id) throw new ApiException('La marca no existe.', 404); return (int) $id; }
function bootstrap(PDO $db, array $actor): array { seedCities($db); normalizeAthleteNames($db); refreshCategories($db); $params = []; $where = ''; if (!hasGlobalMarkAccess($actor)) { $ids = permittedAthleteIds($db, $actor); if (!$ids) { $where = ' WHERE 1 = 0'; } else { $where = ' WHERE id IN (' . implode(',', array_fill(0, count($ids), '?')) . ')'; $params = $ids; } } $athletes = execute($db, "SELECT id, nombre AS name, apellidos AS surname, DATE_FORMAT(fecha_nacimiento, '%Y-%m-%d') AS birthdate, sexo AS sex FROM atletas{$where} ORDER BY apellidos, nombre", $params)->fetchAll(); if (hasGlobalMarkAccess($actor)) { foreach ($athletes as &$athlete) { $athlete['canCreateMarks'] = true; $athlete['canEditMarks'] = true; } } else { $permissions = []; foreach (userPermissions($db, (int) $actor['id']) as $permission) $permissions[(string)$permission['athleteId']] = $permission; foreach ($athletes as &$athlete) { $permission = $permissions[(string)$athlete['id']] ?? []; $athlete['canCreateMarks'] = !empty($permission['canCreate']); $athlete['canEditMarks'] = !empty($permission['canEdit']); } } unset($athlete); $events = events($db); $cities = cities($db); $markParams = []; $markWhere = ''; if (!hasGlobalMarkAccess($actor)) { $ids = permittedAthleteIds($db, $actor); if (!$ids) { $markWhere = ' WHERE 1 = 0'; } else { $markWhere = ' WHERE m.atleta_id IN (' . implode(',', array_fill(0, count($ids), '?')) . ')'; $markParams = $ids; } } $marks = execute($db, marksSelect() . $markWhere . ' ORDER BY m.fecha DESC, m.id DESC', $markParams)->fetchAll(); $users = isAdmin($actor) ? users($db) : []; $translations = translations($db); return compact('athletes', 'events', 'cities', 'marks', 'users', 'translations'); }
function publicMarks(PDO $db): array {
    normalizeAthleteNames($db);
    refreshCategories($db);
    $events = events($db, true);
    $athletes = execute($db, "SELECT DISTINCT a.id, CONCAT(a.nombre, ' ', a.apellidos) AS name FROM atletas a JOIN marcas m ON m.atleta_id = a.id ORDER BY a.apellidos, a.nombre")->fetchAll();
    $categories = execute($db, 'SELECT DISTINCT categoria FROM marcas ORDER BY categoria')->fetchAll(PDO::FETCH_COLUMN);
    $location = locationSql();
    $marks = execute($db, "SELECT m.id, m.atleta_id AS athleteId, m.prueba_id AS eventId, m.ciudad_id AS cityId, CONCAT(a.nombre, ' ', a.apellidos) AS athlete, p.nombre AS event, p.ambito AS area, p.grupo AS eventGroup, CASE p.sentido_resultado WHEN 'mayor' THEN 'higher' ELSE 'lower' END AS resultDirection, m.resultado AS result, m.categoria AS category, DATE_FORMAT(m.fecha, '%Y-%m-%d') AS date, {$location} FROM marcas m JOIN atletas a ON a.id=m.atleta_id JOIN pruebas p ON p.id=m.prueba_id LEFT JOIN ciudades c ON c.id=m.ciudad_id LEFT JOIN pistas t ON t.id=m.pista_id ORDER BY m.creado_en DESC, m.id DESC LIMIT 20")->fetchAll();
    $total = (int) execute($db, 'SELECT COUNT(*) FROM marcas')->fetchColumn();
    return ['events' => $events, 'athletes' => $athletes, 'categories' => $categories, 'marks' => $marks, 'translations' => translations($db), 'counts' => ['athletes' => count($athletes), 'events' => count($events), 'marks' => $total]];
}
function publicRanking(PDO $db, ?string $area, ?string $eventGroup, ?int $eventId, ?string $category, ?string $sex): array {
    if ($sex !== null && !in_array($sex, ['femenino', 'masculino'], true)) throw new ApiException('Indica un sexo valido.');
    if ($area === null && $eventGroup === null && $eventId === null && $category === null && $sex === null) throw new ApiException('Selecciona una prueba, una categoria o un sexo.');
    refreshCategories($db);
    $filters = [];
    $params = [];
    if ($area !== null) { $filters[] = 'p.ambito = ?'; $params[] = $area; }
    if ($eventGroup !== null) { $filters[] = 'p.grupo = ?'; $params[] = $eventGroup; }
    if ($eventId !== null) { $filters[] = 'm.prueba_id = ?'; $params[] = $eventId; }
    if ($category !== null) { $filters[] = 'm.categoria = ?'; $params[] = $category; }
    if ($sex !== null) { $filters[] = 'a.sexo = ?'; $params[] = $sex; }
    $availableFilters = [];
    $availableParams = [];
    if ($category !== null) { $availableFilters[] = 'm.categoria = ?'; $availableParams[] = $category; }
    if ($sex !== null) { $availableFilters[] = 'a.sexo = ?'; $availableParams[] = $sex; }
    $availableWhere = $availableFilters ? ' WHERE ' . implode(' AND ', $availableFilters) : '';
    $available = execute($db, "SELECT DISTINCT p.id, p.nombre AS name, p.ambito AS area, p.grupo AS eventGroup FROM marcas m JOIN atletas a ON a.id=m.atleta_id JOIN pruebas p ON p.id=m.prueba_id{$availableWhere} ORDER BY " . eventOrderSql(), $availableParams)->fetchAll();
    $location = locationSql();
    $rows = execute($db, "SELECT m.id,m.atleta_id AS athleteId,m.prueba_id AS eventId,m.ciudad_id AS cityId,CONCAT(a.nombre,' ',a.apellidos) AS athlete,p.nombre AS event,p.ambito AS area,p.grupo AS eventGroup,CASE p.sentido_resultado WHEN 'mayor' THEN 'higher' ELSE 'lower' END AS resultDirection,m.resultado AS result,m.categoria AS category,DATE_FORMAT(m.fecha,'%Y-%m-%d') AS date,{$location} FROM marcas m JOIN atletas a ON a.id=m.atleta_id JOIN pruebas p ON p.id=m.prueba_id LEFT JOIN ciudades c ON c.id=m.ciudad_id LEFT JOIN pistas t ON t.id=m.pista_id WHERE ".implode(' AND ', $filters), $params)->fetchAll();
    $combineCategories = $category === null;
    $grouped = [];
    foreach ($rows as $row) {
        $row['_value'] = comparableResult($row['result']);
        $key = $row['eventId'] . '|' . ($combineCategories ? '' : $row['category']);
        $athlete = (string) $row['athleteId'];
        if (!isset($grouped[$key])) {
            $grouped[$key] = ['event' => ['id' => $row['eventId'], 'name' => $row['event'], 'area' => $row['area'], 'eventGroup' => $row['eventGroup']], 'category' => $combineCategories ? null : $row['category'], 'marks' => []];
        }
        $old = $grouped[$key]['marks'][$athlete] ?? null;
        if (!$old || ($row['resultDirection'] === 'higher' ? $row['_value'] > $old['_value'] : $row['_value'] < $old['_value'])) $grouped[$key]['marks'][$athlete] = $row;
    }
    $groups = array_values($grouped);
    foreach ($groups as &$group) {
        $group['marks'] = array_values($group['marks']);
        usort($group['marks'], static fn($a, $b) => $a['resultDirection'] === 'higher' ? ($b['_value'] <=> $a['_value']) : ($a['_value'] <=> $b['_value']));
        foreach ($group['marks'] as &$mark) unset($mark['_value']);
    }
    return compact('area', 'eventGroup', 'eventId', 'category', 'sex', 'available', 'groups');
}
function publicHistory(PDO $db, int $id): array { refreshCategories($db); $athlete=execute($db,"SELECT id, CONCAT(nombre,' ',apellidos) AS name FROM atletas WHERE id = ?",[$id])->fetch(); if(!$athlete)throw new ApiException('El atleta indicado no existe.',404);$location=locationSql();$marks=execute($db,"SELECT m.id,m.atleta_id AS athleteId,m.prueba_id AS eventId,m.ciudad_id AS cityId,p.nombre AS event,p.ambito AS area,p.grupo AS eventGroup,CASE p.sentido_resultado WHEN 'mayor' THEN 'higher' ELSE 'lower' END AS resultDirection,m.resultado AS result,m.categoria AS category,DATE_FORMAT(m.fecha,'%Y-%m-%d') AS date,{$location} FROM marcas m JOIN pruebas p ON p.id=m.prueba_id LEFT JOIN ciudades c ON c.id=m.ciudad_id LEFT JOIN pistas t ON t.id=m.pista_id WHERE m.atleta_id=? ORDER BY m.fecha DESC",[$id])->fetchAll();return compact('athlete','marks'); }

function writeAthlete(PDO $db, array $payload, ?int $id = null): void { $birthdate=requiredDate($payload,'birthdate','fecha de nacimiento');$sex=requiredSex($payload);$values=[titleCaseName(requiredText($payload,'name','nombre')),titleCaseName(requiredText($payload,'surname','apellidos')),$birthdate,$sex]; if($id===null){execute($db,'INSERT INTO atletas (nombre, apellidos, fecha_nacimiento, sexo) VALUES (?, ?, ?, ?)', $values);return;} ensureExists($db,'atletas',$id);$values[]=$id;execute($db,'UPDATE atletas SET nombre=?, apellidos=?, fecha_nacimiento=?, sexo=? WHERE id=?',$values); foreach(execute($db,'SELECT id, fecha FROM marcas WHERE atleta_id=?',[$id])->fetchAll() as $mark) execute($db,'UPDATE marcas SET categoria=? WHERE id=?',[categoryForDates($birthdate,$mark['fecha'],$sex),$mark['id']]); }
function moveAthleteMarks(PDO $db,array $payload): array{$sourceId=requiredId($payload,'sourceAthleteId','atleta origen');$targetId=requiredId($payload,'targetAthleteId','atleta destino');if($sourceId===$targetId)throw new ApiException('El atleta origen y destino deben ser diferentes.');ensureExists($db,'atletas',$sourceId);$target=execute($db,'SELECT fecha_nacimiento, sexo FROM atletas WHERE id=?',[$targetId])->fetch();if(!$target)throw new ApiException('El atleta destino no existe.',404);$marks=execute($db,'SELECT id, fecha FROM marcas WHERE atleta_id=?',[$sourceId])->fetchAll();foreach($marks as $mark){$category=categoryForDates($target['fecha_nacimiento'],$mark['fecha'],$target['sexo']);execute($db,'UPDATE marcas SET atleta_id=?, categoria=? WHERE id=?',[$targetId,$category,$mark['id']]);}return ['moved'=>count($marks)];}
function markPayload(PDO $db, array $payload): array { $athleteId=requiredId($payload,'athleteId','atleta');$eventId=requiredId($payload,'eventId','prueba');$cityId=requiredId($payload,'cityId','ciudad');$date=requiredDate($payload,'date','fecha');$athlete=execute($db,'SELECT fecha_nacimiento, sexo FROM atletas WHERE id=?',[$athleteId])->fetch();$event=execute($db,'SELECT informacion_adicional, ambito FROM pruebas WHERE id=?',[$eventId])->fetch();if(!$athlete||!$event)throw new ApiException('El atleta o prueba no existe.');ensureExists($db,'ciudades',$cityId);$technical=optionalText($payload,'technicalInfo');if((bool)$event['informacion_adicional']&&!$technical)throw new ApiException('La caracteristica tecnica es obligatoria para esta prueba.');$track=optionalText($payload,'trackName');return [$athleteId,$eventId,$cityId,$track,$date,requiredResult($payload),$technical,categoryForDates($athlete['fecha_nacimiento'],$date,$athlete['sexo'])]; }
function writeMark(PDO $db, array $payload, array $actor, ?int $id=null): void { $values=markPayload($db,$payload); $athleteId = (int) $values[0]; if($id===null){requireAthletePermission($db,$actor,$athleteId,'create');$values[]=(int)$actor['id'];$values[]=(int)$actor['id'];execute($db,'INSERT INTO marcas (atleta_id,prueba_id,ciudad_id,nombre_pista,fecha,resultado,caracteristica_tecnica,categoria,creado_por,actualizado_por) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',$values);return;} $oldAthleteId=markAthleteId($db,$id);requireAthletePermission($db,$actor,$oldAthleteId,'edit');if($athleteId!==$oldAthleteId&&!hasGlobalMarkAccess($actor))throw new ApiException('No puedes cambiar la marca a otro atleta.',403);$values[]=(int)$actor['id'];$values[]=$id;execute($db,'UPDATE marcas SET atleta_id=?,prueba_id=?,ciudad_id=?,nombre_pista=?,fecha=?,resultado=?,caracteristica_tecnica=?,categoria=?,actualizado_por=? WHERE id=?',$values); }
function importAthletes(PDO $db, array $payload): array { $rows=$payload['athletes']??null;if(!is_array($rows))throw new ApiException('No se han recibido atletas.');$imported=$updated=$duplicates=$invalid=0;foreach($rows as $row){try{if(!empty($row['id'])){writeAthlete($db,$row,(int)$row['id']);$updated++;}else{writeAthlete($db,$row);$imported++;}}catch(PDOException $e){if($e->getCode()==='23000')$duplicates++;else throw $e;}catch(ApiException){$invalid++;}}return compact('imported','updated','duplicates','invalid'); }
function importCities(PDO $db,array $payload): array{$rows=$payload['cities']??null;if(!is_array($rows))throw new ApiException('No se han recibido ciudades.');$count=0;$s=$db->prepare('INSERT IGNORE INTO ciudades (nombre, provincia) VALUES (?, ?)');foreach($rows as $row){if(!is_array($row)||trim((string)($row['name']??''))==='')continue;$s->execute([trim($row['name']),trim((string)($row['province']??''))]);$count+=$s->rowCount();}return ['imported'=>$count];}
function importMarks(PDO $db,array $payload,array $actor): array{$rows=$payload['marks']??null;if(!is_array($rows))throw new ApiException('No se han recibido marcas.');$athleteId=requiredId($payload,'athleteId','atleta');ensureExists($db,'atletas',$athleteId);requireAthletePermission($db,$actor,$athleteId,'create');$errors=[];$valid=[];foreach($rows as $index=>$row){try{if(!is_array($row))throw new ApiException('Fila no valida.');$row['athleteId']=$athleteId;$valid[]=$row;markPayload($db,$row);}catch(ApiException $e){$errors[]=['row'=>$index+2,'error'=>$e->getMessage()];}}if($errors)return ['imported'=>0,'errors'=>$errors];foreach($valid as $row)writeMark($db,$row,$actor);return ['imported'=>count($valid),'errors'=>[]];}
function importMultipleMarks(PDO $db,array $payload,array $actor): array{$rows=$payload['marks']??null;if(!is_array($rows))throw new ApiException('No se han recibido marcas.');$errors=[];$valid=[];foreach($rows as $index=>$row){try{if(!is_array($row))throw new ApiException('Fila no valida.');$values=markPayload($db,$row);requireAthletePermission($db,$actor,(int)$values[0],'create');$valid[]=$row;}catch(ApiException $e){$errors[]=['row'=>(int)($row['_line']??$index+2),'error'=>$e->getMessage()];}}if($errors)return ['imported'=>0,'errors'=>$errors];foreach($valid as $row)writeMark($db,$row,$actor);return ['imported'=>count($valid),'errors'=>[]];}
function replaceMarkFields(PDO $db,array $payload): array{$field=(string)($payload['field']??'');$search=requiredText($payload,'search','buscar');$replace=(string)($payload['replace']??'');if(!in_array($field,['city','trackName'],true))throw new ApiException('Indica si quieres reemplazar ciudad o pista.');if($field==='trackName'){$statement=$db->prepare('UPDATE marcas SET nombre_pista = REPLACE(COALESCE(nombre_pista, ""), ?, ?) WHERE nombre_pista LIKE ?');$statement->execute([$search,$replace,'%'.$search.'%']);return ['updated'=>$statement->rowCount()];}$sourceId=filter_var($payload['searchCityId']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);$targetId=filter_var($payload['replaceCityId']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if($sourceId&&$targetId){ensureExists($db,'ciudades',(int)$sourceId);ensureExists($db,'ciudades',(int)$targetId);$statement=$db->prepare('UPDATE marcas SET ciudad_id = ? WHERE ciudad_id = ?');$statement->execute([(int)$targetId,(int)$sourceId]);return ['updated'=>$statement->rowCount()];}$updated=0;foreach(execute($db,'SELECT id, nombre, provincia FROM ciudades')->fetchAll() as $city){if(stripos($city['nombre'],$search)===false)continue;$targetName=str_ireplace($search,$replace,$city['nombre']);$target=execute($db,'SELECT id FROM ciudades WHERE nombre = ? AND provincia <=> ? LIMIT 1',[$targetName,$city['provincia']])->fetch();if(!$target){execute($db,'INSERT INTO ciudades (nombre, provincia) VALUES (?, ?)',[$targetName,$city['provincia']]);$newTargetId=(int)$db->lastInsertId();}else{$newTargetId=(int)$target['id'];}$statement=$db->prepare('UPDATE marcas SET ciudad_id = ? WHERE ciudad_id = ?');$statement->execute([$newTargetId,$city['id']]);$updated+=$statement->rowCount();}return ['updated'=>$updated];}
function writeTranslation(PDO $db,array $payload,?int $id=null):void{$values=[requiredText($payload,'literal','literal'),requiredText($payload,'es','castellano'),requiredText($payload,'ca','catalan')];if($id===null){execute($db,'INSERT INTO traducciones (literal,castellano,catalan) VALUES (?, ?, ?)',$values);return;}ensureExists($db,'traducciones',$id);$values[]=$id;execute($db,'UPDATE traducciones SET literal=?,castellano=?,catalan=? WHERE id=?',$values);}

function route(PDO $db,string $method,string $path,array $payload): array {
 if($method==='GET'&&$path==='/auth/status'){return [['setupRequired'=>(int)execute($db,'SELECT COUNT(*) FROM usuarios')->fetchColumn()===0,'user'=>currentUser($db)],200];}
 if($method==='POST'&&$path==='/auth/setup'){if((int)execute($db,'SELECT COUNT(*) FROM usuarios')->fetchColumn()!==0)throw new ApiException('La configuracion inicial ya se ha realizado.',409);$_SESSION['user_id']=createUser($db,$payload,true);seedCatalogue($db);session_regenerate_id(true);return [['user'=>currentUser($db)],201];}
 if($method==='POST'&&$path==='/auth/login'){$user=execute($db,'SELECT id,password_hash,activo FROM usuarios WHERE usuario=?',[requiredUsername($payload)])->fetch();if(!$user||!(bool)$user['activo']||!password_verify((string)($payload['password']??''),$user['password_hash']))throw new ApiException('Usuario o contrasena incorrectos.',401);$_SESSION['user_id']=(int)$user['id'];session_regenerate_id(true);return [['user'=>currentUser($db)],200];}
 if($method==='POST'&&$path==='/auth/logout'){unset($_SESSION['user_id']);return [['ok'=>true],200];}
 if($method==='GET'&&$path==='/public/translations')return [['translations'=>translations($db)],200];
 if($method==='GET'&&$path==='/public/marks')return [publicMarks($db),200];
 if($method==='GET'&&$path==='/public/ranking'){$raw=trim((string)($_GET['eventId']??''));$id=$raw===''?null:filter_var($raw,FILTER_VALIDATE_INT);return [publicRanking($db,trim((string)($_GET['area']??''))?:null,trim((string)($_GET['eventGroup']??''))?:null,$id?(int)$id:null,trim((string)($_GET['category']??''))?:null,trim((string)($_GET['sex']??''))?:null),200];}
 if($method==='GET'&&preg_match('#^/public/athletes/(\d+)/history$#',$path,$m))return [publicHistory($db,(int)$m[1]),200];
 $actor=requireUser($db);
 if($method==='POST'&&$path==='/auth/password'){changePassword($db,$payload,$actor);return [['ok'=>true],200];}
 if($method==='GET'&&$path==='/bootstrap')return [bootstrap($db,$actor),200];
 if($method==='POST'&&$path==='/events/seed'){requireAdmin($actor);seedCatalogue($db);return [['ok'=>true],201];}
 if($method==='POST'&&$path==='/athletes/move-marks'){requireAdmin($actor);return [moveAthleteMarks($db,$payload),200];}
 if($method==='POST'&&$path==='/athletes/import'){requireAdmin($actor);return [importAthletes($db,$payload),200];}
 if($method==='POST'&&$path==='/cities/import'){requireAdmin($actor);return [importCities($db,$payload),200];}
 if($method==='POST'&&$path==='/cities/merge'){requireAdmin($actor);return [mergeCities($db,$payload),200];}
 if($method==='POST'&&$path==='/marks/import'){requireAdmin($actor);return [importMarks($db,$payload,$actor),200];}
 if($method==='POST'&&$path==='/marks/import/multiple'){requireAdmin($actor);return [importMultipleMarks($db,$payload,$actor),200];}
 if($method==='POST'&&$path==='/marks/replace'){requireGlobalMarkAccess($actor);return [replaceMarkFields($db,$payload),200];}
 if($method==='POST'&&$path==='/users'){requireAdmin($actor);createUser($db,$payload);return [['ok'=>true],201];}
 if($method==='POST'&&$path==='/events'){requireAdmin($actor);writeEvent($db,$payload);return [['ok'=>true],201];}
 if($method==='POST'&&$path==='/athletes'){requireAdmin($actor);writeAthlete($db,$payload);return [['ok'=>true],201];}
 if($method==='POST'&&$path==='/cities'){requireAdmin($actor);writeCity($db,$payload);return [['ok'=>true],201];}
 if($method==='POST'&&$path==='/marks'){writeMark($db,$payload,$actor);return [['ok'=>true],201];}
 if($method==='POST'&&$path==='/translations'){requireAdmin($actor);writeTranslation($db,$payload);return [['ok'=>true],201];}
 if(preg_match('#^/(users|events|athletes|cities|marks|translations)/(\d+)$#',$path,$m)){$resource=$m[1];$id=(int)$m[2];if($method==='PUT'){if($resource==='users'){requireAdmin($actor);updateUser($db,$id,$payload,$actor);}elseif($resource==='events'){requireAdmin($actor);writeEvent($db,$payload,$id);}elseif($resource==='athletes'){requireAnyAthletePermission($db,$actor,$id);writeAthlete($db,$payload,$id);}elseif($resource==='cities'){requireAdmin($actor);writeCity($db,$payload,$id);}elseif($resource==='marks'){writeMark($db,$payload,$actor,$id);}else{requireAdmin($actor);writeTranslation($db,$payload,$id);}return [['ok'=>true],200];}if($method==='DELETE'){if($resource==='marks'){requireAthletePermission($db,$actor,markAthleteId($db,$id),'edit');execute($db,'DELETE FROM marcas WHERE id=?',[$id]);}elseif($resource==='users'){requireAdmin($actor);deleteUser($db,$id,$actor);}else{requireAdmin($actor);$table=['events'=>'pruebas','athletes'=>'atletas','cities'=>'ciudades','translations'=>'traducciones'][$resource];ensureExists($db,$table,$id);if($resource==='cities'&&(int)execute($db,'SELECT COUNT(*) FROM marcas WHERE ciudad_id=?',[$id])->fetchColumn()>0)throw new ApiException('No se puede eliminar una ciudad con marcas asociadas. Fusiona la ciudad primero.',409);execute($db,"DELETE FROM {$table} WHERE id=?",[$id]);}return [['ok'=>true],200];}}
 throw new ApiException('Ruta no encontrada.',404);
}
try{$method=strtoupper($_SERVER['REQUEST_METHOD']??'GET');$payload=in_array($method,['POST','PUT'],true)?input():[];$db=connection();$db->beginTransaction();[$response,$status]=route($db,$method,path(),$payload);$db->commit();respond($response,$status);}catch(ApiException $e){if(isset($db)&&$db->inTransaction())$db->rollBack();respond(['error'=>$e->getMessage()],$e->status);}catch(PDOException $e){if(isset($db)&&$db->inTransaction())$db->rollBack();respond(['error'=>$e->getCode()==='23000'?'Ya existe un registro con esos datos o tiene marcas asociadas.':'Error de base de datos.'],$e->getCode()==='23000'?409:500);}catch(Throwable $e){if(isset($db)&&$db->inTransaction())$db->rollBack();respond(['error'=>'Error interno del servidor.'],500);}
